PX4/PX4-ECL

EKF/ekf.cpp

Fixes incorrect initialisation of vehicle orientation that contributed to large angular HUD movement for the first few seconds after startup.
Uses the gravity vector to estimate the initial roll and pitch angle
Uses the projection of the magnetic field measurement onto the earth axis horizontal plane to calculate the initial heading
TODO: implement an alignment state machine that does tilt -> yaw -> GPS with health checks at each state transition.

EKF: Fix 'Dizzy on Startup' behaviour

---

EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_base.cpp
EKF/vel_pos_fusion.cpp

Several fixes for ekf2. Filter is now using full mag vector fusion.

Ekf2 fixes

---

CMakeLists.txt
EKF/RingBuffer.h
EKF/common.h
EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_base.cpp
EKF/estimator_base.h
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/gps_checks.cpp
EKF/mag_fusion.cpp
EKF/vel_pos_fusion.cpp

This started out as work to add GPS innovation checks and fusion control model logic, but during the work it was discovered that the split of functionality between the Ekf and estimator_base classes was making integration of new functions more difficult than desired.
GPS and Baro alt innovation consistency checks have been added.
Fusion control logic has been added to enable automatic transition between GPS and non-GPS operation.
The EstimatorBase class has been made thinner, only contains those functions and variables required to interface to data and parameters and has been renamed the EstimatorInterface class. All other functions and variables have been moved to the Ekf class.
Finally ./Tools/fix_code_style.sh was run on the code to fix style differences.
This branch (and it's …

Modify structure to improve maintainability and add fusion control logic

---

EKF/ekf_helper.cpp
EKF/vel_pos_fusion.cpp

Moved it since it is a general function used not only for velocity and position fusion

moved fuse function to ekf_helper.cpp

---

.gitignore
.gitmodules
.travis.yml
EKF/CMakeLists.txt
EKF/covariance.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/geo.cpp
EKF/geo.h
EKF/gps_checks.cpp
EKF/mag_fusion.cpp
EKF/mathlib.cpp
EKF/mathlib.h
README.md
build.sh

This PR enables standalone build for ECL's EKF library.

Shared Library build

---

EKF/common.h
EKF/ekf.cpp
EKF/ekf.h
EKF/estimator_interface.cpp
EKF/estimator_interface.h

Hello,
This pull request replaces PR#50. 
It is submitted to make provision for C99 compatibility such that C11 incompatible microprocessor IDEs may compile the library.
Thanks for your feedback!
-Mark

Address C99 compatibility issues by relocating variable initialization. - Replaces PR#50

---

EKF/covariance.cpp
EKF/ekf.cpp
EKF/mag_fusion.cpp

Fixes a bug that causes alignment failure when inverted
Improves initial covariance values for smoother alignment

Improvements to EKF startup - partially replaces PR#57

---

attitude_fw/ecl_pitch_controller.cpp
attitude_fw/ecl_roll_controller.cpp
attitude_fw/ecl_wheel_controller.cpp
attitude_fw/ecl_yaw_controller.cpp

Otherwise the transition can be quite abrupt when tuning.

fw multiply integrator gain in loop

---

CMakeLists.txt
EKF/tests/base/CMakeLists.txt
EKF/tests/ringbuffer/CMakeLists.txt

Removes a cmake warning in PX4.

cmake STACK -> STACK_MAIN

---

EKF/airspeed_fusion.cpp
EKF/common.h
EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/estimator_interface.cpp
EKF/estimator_interface.h

- finished logic for fusion
- fixed bug where previous control status was set in the wrong location

ekf2 airspeed fusion:

---

l1/ecl_l1_pos_controller.h

Accompanies https://github.com/PX4/Firmware/pull/4363

L1 initialize everything

---

EKF/ekf.cpp

Another fix like https://github.com/PX4/Firmware/pull/4374.

ekf: compile fix for Ubuntu 16.04

---

EKF/ekf_helper.cpp

after a height reset zero the cross covariances for height and vertical velocity states. this should prevent accel bias and height states covariances
to get negative after a height reset.

after a height reset zero the cross covariances for height and vertical

---

EKF/CMakeLists.txt
EKF/airspeed_fusion.cpp
EKF/gps_checks.cpp
EKF/vel_pos_fusion.cpp

I'm trying to enable -Wshadow in PX4 and found another declaration of KH and KHP when I'm assuming the version in the Ekf class was intended to be used.

enable Wshadow

---

EKF/airspeed_fusion.cpp
EKF/estimator_interface.h

@tumbili I think there was a bug that the airspeed_healthy flag was never set to true?

fixed_airspeed_healthy_bug

---

EKF/common.h
EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/gps_checks.cpp
EKF/terrain_estimator.cpp

Uses a single externally set in-air status flag.

Remove reliance on vehicle arm status

---

EKF/common.h

Will test this later in the week

Changed airspeed innovation gate to 10

---

EKF/airspeed_fusion.cpp

_fault_status.bad_airspeed was never set

added bad_airspeed reporting

---

EKF/common.h
EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/mag_fusion.cpp
EKF/vel_pos_fusion.cpp

Replaces #101 
@devbharat Can you please test this and report back. Before I merge this PR I need  a matching PR on the PX4/Firmware side that includes the changes to logging and replay so the vision aiding can be tested, debugged and tuned off-line.

EKF: add support for external vision data

---

EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/vel_pos_fusion.cpp

Bench tested across range of orientations

EKF: Improve angular alignment consistency

---

EKF/ekf_helper.cpp

Improves reset of quaternion covariance matrix after a heading reset by preserving variance in roll and pitch and resetting yaw variance to the measurement variance.
This allows yaw errors to be learned faster and does not leave the attitude vulnerable to IMU errors for the first few seconds after the reset.
It has been tested with pitch attitude of 90 degrees on alignment and heading reset:
http://logs.uaventure.com/view/kWNqkU7KapSSrveTsLz6td
and a normal start and takeoff from level:
http://logs.uaventure.com/view/ouqgezdzjkm5E6HchmL4yB
I am seeking a tail-sitter replay log to finalise testing

EKF: Improved heading reset

---

EKF/covariance.cpp

Fixed typo in the check when updating the body field variance

updated logic of calculation of body field variance

---

EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/mag_fusion.cpp
EKF/vel_pos_fusion.cpp

Was reading through the code anyway so fixed some typos

fixed some typos

---

EKF/ekf.cpp

@priseborough Seemed that we were calculating the same thing twice?

Deleted second update of transformation matrix

---

EKF/estimator_interface.cpp

Fixes https://github.com/PX4/ecl/issues/103#issuecomment-220959079

EKF: prevent unwanted GPS use

---

EKF/ekf.cpp

Don't initialise the states for the alignment data noise filters until the buffers have been flushed
Flight test here: http://logs.uaventure.com/view/VqZZmDJrjFVMwi8zDeAT5d

EKF: Initialise alignment noise filters using valid data

---

EKF/ekf_helper.cpp

@priseborough I think the code was returning too early in the velocity reset method.

do not return early in velocity reset method

---

EKF/mag_fusion.cpp

Perform the innovation consistency check on all axes first and exit if any axis fails. Reduces the likelihood of bad magnetometer data corrupting the attitude estimates.
Addresses #170

EKF: perform innovation check in all axes before fusing 3D mag data

---

EKF/control.cpp

- this solves the issue where height innovations would jump
between two regimes

fixed wrong condition on which gps height would be fused

---

EKF/airspeed_fusion.cpp
EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.h
matlab/scripts/Inertial Nav EKF/polar2cart_cov.m

@tumbili @priseborough 
This was tested successfully today. Very short flight and some pitot offset but the data looks good to me.
log is [here](http://logs.uaventure.com/view/rYeLRcDS4X9FUTJvDACTjH)

Fix wind state  and wind variance initialization

---

EKF/estimator_interface.cpp

fixed computation of range measurement timestamp

---

attitude_fw/ecl_pitch_controller.cpp

-limit body fixed turn offset contrained roll to possible
roll setpoint range
-fixes #181

ecl attitude_fw fix excessive body fixed turn offset

---

EKF/airspeed_fusion.cpp

Addresses https://github.com/PX4/ecl/issues/205

EKF: Reduce effect of bad airspeed when other aiding data available

---

EKF/airspeed_fusion.cpp
EKF/ekf.h
EKF/mag_fusion.cpp
EKF/optflow_fusion.cpp

KH doesn't need to be a class variable so this will save 24x24x4 bytes

EKF: save some stack space

---

EKF/airspeed_fusion.cpp
EKF/mag_fusion.cpp
EKF/optflow_fusion.cpp

EKF: reduce KH to only the elements that are really needed, and merge the loops

---

validation/data_validator.cpp
validation/data_validator.h
validation/data_validator_group.cpp
validation/data_validator_group.h

@pavel-kirienko This fixes your issue in a more scalable fashion.

Make the equal value threshold configurable

---

validation/data_validator_group.cpp

Fixed include for snapdragon

---

EKF/control.cpp
EKF/ekf.cpp
EKF/estimator_interface.cpp
EKF/gps_checks.cpp

Addresses https://github.com/PX4/ecl/issues/225
Combine the observation action buffer and alignment messages
Ensure all data timeout messages are warnings.
Use consistent terminology.

EKF: Rationalise console messages

---

EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h

Splits reporting for local and global position errors.
Adds reporting for local velocity errors.

EKF: Improve reporting of position and velocity accuracy

---

.travis.yml
CMakeLists.txt
EKF/CMakeLists.txt
EKF/ekf_helper.cpp
EKF/mathlib.h
build.sh

- update matrix to latest (matches PX4)
- trivial cmake cleanup
- travis-ci build with both gcc and clang
- closes #240

cmake add all EKF sources

---

EKF/ekf.cpp

This pull request addresses the issue discussed in #224 .

height counter update for ev primary height source

---

EKF/covariance.cpp

This bug caused X and Y delta velocity bias state variance to be reset to the same value as the Z axis when learning was inhibited. Documentation has also been updated.  
The effect of this error was subtle. Here are the accel delta velocity bias states before and after the change from a log that causes frequent activation of the bias learning  inhibit logic:
**Before**
**After**
Here are the corresponding delta velocity bias state variances before and after the change - note that before the change, the state variances for the three axes are identical for most of the flight:
**Before**
**After**

EKF: Fix bug in accelerometer bias learning inhibit

---

EKF/mag_fusion.cpp

See associated changes in https://github.com/PX4/Firmware/pull/7332

Fix compilation errors with GCC 7

---

EKF/control.cpp

Here are some fixes that should solve the remaining issues when using range aid.

Pr range aid fixes

---

EKF/common.h
EKF/control.cpp
EKF/covariance.cpp

Addresses https://github.com/PX4/ecl/issues/287#issuecomment-311957675
Needs flight or replay log testing.

EKF: Fix bug affecting wind estimation for planes

---

EKF/common.h
EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h

Adjusts yaw by the amount of the error between GPS and EKF course if innovations are large.

EKF: Enable planes to recover from bad mag data at start of flight

---

EKF/control.cpp

Addresses https://github.com/PX4/Firmware/issues/7491#issuecomment-312613868

EKF: Allow fallback to non-aiding mode if external vision fusion is lost

---

EKF/terrain_estimator.cpp

fix for https://github.com/PX4/ecl/issues/299#issuecomment-314837283

return hagl valid false if update was rejected

---

matlab/EKF_replay/Common/convert_px4_sensor_combined_csv_data.m

needed by https://github.com/PX4/Firmware/pull/7602 
Signed-off-by: Nicolae Rosia <nicolae.rosia@gmail.com>

sensor_combined stores deltas in usec instead of seconds

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
EKF/terrain_estimator.cpp

So we don't have to use dummy variables to check if terrain is valid

Split get_terrain_vert_pos() into valid and get_vpos

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
EKF/terrain_estimator.cpp

Revert "Split get_terrain_vert_pos() into valid and get_vpos"

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
EKF/terrain_estimator.cpp

Revert "Revert "Split get_terrain_vert_pos() into valid and get_vpos""

---

EKF/mag_fusion.cpp

The yaw angle fusion can either use the measured magnetic field projected onto the horizontal or quaternions from an external vision system. When using external vision quaternions, the calculations for projection of the magnetic field were still being performed.
This PR moves the mag field projection and yaw calculation into the if (_control_status.flags.mag_hdg) branch. It also replaces the conversion from the External Vision quaternions with a more efficient direct calculation with a referenced derivation.
A log from testing with a wide range of ground rotations including those performed during a mag calibration sequence can be found here: 
http://logs.px4.io/plot_app?log=a174c2b2-af05-404e-a242-f32843c3b06b

EKF: Improve efficiency of yaw fusion for External Vision 

---

EKF/airspeed_fusion.cpp
EKF/ekf.h
EKF/estimator_interface.h
EKF/mag_fusion.cpp

Adds an accessor for true airspeed.

EKF: Add true airspeed accessor

---

EKF/control.cpp
EKF/ekf.h
EKF/terrain_estimator.cpp

@priseborough Is this somewhat what you were thinking of (https://github.com/PX4/ecl/pull/307#issuecomment-316368891)?

Pr check stuck rng

---

EKF/RingBuffer.h
EKF/airspeed_fusion.cpp
EKF/control.cpp
EKF/covariance.cpp
EKF/drag_fusion.cpp
EKF/ekf.cpp
EKF/ekf_helper.cpp
EKF/geo.cpp
EKF/mag_fusion.cpp
EKF/optflow_fusion.cpp
EKF/sideslip_fusion.cpp
ecl.h

Mostly minor white space, except sideslip_fusion.cpp which was a horrible mix of tabs and spaces.

EKF trivial code style cleanup

---

EKF/control.cpp
EKF/ekf.cpp
EKF/ekf_helper.cpp

See https://github.com/PX4/Firmware/pull/7908

EKF: use hamiltonian convention for quaternion multiplication order

---

EKF/estimator_interface.h

just a small get function that I need for a check

add function to get in air status

---

EKF/ekf_helper.cpp

replaces https://github.com/PX4/ecl/pull/340

EKF: If aligning yaw for fw with low GPS velocity, use mag

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/mag_fusion.cpp

Fixes https://github.com/PX4/ecl/issues/352
See issue for explanation and preliminary test results using replay of FW logs.
The RW testing is still outstanding and will be completed tomorrow.

Prevent loss of navigation accuracy after in-flight mag yaw alignment

---

EKF/common.h
EKF/control.cpp

https://github.com/PX4/ecl/issues/284

EKF: Remove redundant code

---

EKF/common.h
EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/vel_pos_fusion.cpp

See https://github.com/PX4/Firmware/pull/8160 for details

EKF: Add additional velocity interface to use landing beacon data

---

EKF/control.cpp

Fixes https://github.com/PX4/ecl/issues/363

EKF: Don't print navigation lost message on startup

---

EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h

Also requires changes on the [firmware side](https://github.com/PX4/Firmware/pull/8489)

ekf: return beta test ratio in get_innovation_test_status

---

EKF/ekf.h

EKF initialize _hvelInnovGate

---

EKF/control.cpp

It should use index 9 for vertical position.
Fixes https://github.com/PX4/ecl/issues/385

EKF: fix indexing bug

---

EKF/ekf.cpp

this also makes sure `_baro_hgt_offset` is being initialized correctly

init height using baro when set to ev height

---

l1/ecl_l1_pos_controller.cpp
l1/ecl_l1_pos_controller.h
tecs/tecs.cpp
tecs/tecs.h

PX4 Firmware side - https://github.com/PX4/Firmware/pull/9101

TECS and L1 switch to matrix math library

---

airdata/WindEstimator.hpp
l1/ecl_l1_pos_controller.h
tecs/tecs.h

Trivial include update needed for https://github.com/PX4/Firmware/pull/9181.

update matrix lib usage

---

EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h

https://github.com/PX4/ecl/pull/413#issuecomment-383314867
Any consumer can independently check the validity flags, or in the case of global position won't even have a publication.

EKF always fill position and velocity accuracy

---

geo_lookup/geo_mag_declination.cpp

The lookup table max was not being constrained to within table bounds - 1 as described in the comment.
https://github.com/PX4/Firmware/pull/9421#issuecomment-386843684

geo_lookup fix table bounds

---

EKF/ekf.cpp

Fixes https://github.com/PX4/ecl/issues/430

remove superfluous elseif

---

geo/geo.cpp

-this doesn't seem to be (obviously?) available on qurt
@RomanBapst FYI

geo remove use of DBL_EPSILON

---

EKF/CMakeLists.txt
airdata/CMakeLists.txt
attitude_fw/CMakeLists.txt
geo/CMakeLists.txt
geo_lookup/CMakeLists.txt
l1/CMakeLists.txt
tecs/CMakeLists.txt
validation/CMakeLists.txt

- this is needed for INFO, WARN, ERR messages when used within PX4

set MODULE define for each library

---

attitude_fw/ecl_wheel_controller.cpp
geo/geo.cpp
geo/geo.h
l1/ecl_l1_pos_controller.cpp
l1/ecl_l1_pos_controller.h

Requires https://github.com/PX4/Matrix/pull/68 for wrap_2pi.

replace geo _wrap_pi with matrix::wrap_pi

---

tecs/tecs.cpp

For testing purposes or also if one just does not want to use an integrator, users can set the TECS `_integrator_gain` to zero. However, this results in undesired behavior:
- If one starts with `_integrator_gain!=0` but then sets `_integrator_gain=0` during flight for testing/tuning, then `_pitch_integ_state` and `_throttle_integ_state` can potentially remain at large values, thus heavily disturbing the control loop.
- Even if one starts with `_integrator_gain=0`, a climbout (e.g. autonomous takeoff via Pixhawk autopilot) will force certain integrator state values e.g. [here](https://github.com/PX4/ecl/blob/master/tecs/tecs.cpp#L373). When the climbout is finished, the integrator will then just remain at that value, again disturbing the control loop! 
See image below: This was a test …

TECS: Fix undesired behaviour when integrator gain is zero

---

geo/geo.cpp

Saves a few double floating point operations.

geo get_bearing_to_next_waypoint() small optimization

---

EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
geo/geo.h

Minor readability change. These can all be evaluated at compile time (math::radians and sq), so there's no functional or even minor performance change.

EKF angle constants in degrees for readability

---

EKF/ekf_helper.cpp

This change fixes a vulnerability where if GPS use is gained, the velocity limiting was removed and the operator could fly the vehicle fast enough to cause the flow sensor to saturate and cause large velocity errors leading to rejection of GPS and loss of navigation.
velocity limiting is now matinee at all times when flow data is being fused, however the height limiting is removed when the vehicle is not completely reliant on flow data. This enables the vehicle to be flown up to an altitude where flow use ceases once GPS fusion has commenced.
**TODO**
Add link to original log or issue illustrating problem.

EKF: Maintain flow sensor velocity limiting

---

CMakeLists.txt

Small change to enable PX4 top level generation.

cmake ignore doxygen if not a standalone build

---

EKF/estimator_interface.cpp

Motion compensated optical flow rates are supposed to be zeroed if flow data is failing validity checks when on ground. This was not being done in the code. The comments and logic have been amended to be consistent and make the design intent clearer.

EKF: Add missing optical flow ground motion protection

---

EKF/estimator_interface.cpp

EKF : Fix type of flow data navigation variable

---

EKF/estimator_interface.cpp
EKF/estimator_interface.h

Once PX4 has an IMU message this will make it slightly easier to insert an IMU message directly.
Small piece of https://github.com/PX4/Firmware/pull/9756.
@dakejahl

EKF add new simple setIMUData() interface

---

EKF/control.cpp

Remove duplicate settings.   Lines 524 and 526 are duplicates.
FYI: @priseborough

EKF/control: Remove duplicate settings

---

EKF/documentation/readme.txt

Fix links to moved files in readme

---

EKF/control.cpp
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/terrain_estimator.cpp

Non functional change to address https://github.com/PX4/ecl/issues/555

EKF add clarity brackets to avoid potential confusion

---

CMakeLists.txt

* https://github.com/PX4/Matrix/commit/6b0777d815cd64902eb0575d56ec52f53aebb4a0

cmake standalone build pin PX4/Matrix to commit

---

README.md

README: Fix link to EKF/ECL tuning guide

---

EKF/control.cpp

Fix for https://github.com/PX4/Firmware/issues/11812
Before this PR  https://review.px4.io/plot_app?log=f1ff8c5b-d47a-4065-8a6a-1beafacd1b6c
With this PR https://review.px4.io/plot_app?log=5fc526f8-01f8-4a85-a7b0-73c3dad57c05

do not reset yaw if vehicle on ground

---

mathlib/mathlib.cpp

Corrected indentation from #606

mathlib: fix floorf indentation

---

EKF/estimator_interface.h

EKF: fix variable names in estimator_interface.h

---

EKF/control.cpp
EKF/ekf_helper.cpp
EKF/gps_yaw_fusion.cpp

fixes https://github.com/PX4/ecl/issues/604

 ekf: correct quaternion multiplication order

---

airdata/WindEstimator.cpp
airdata/WindEstimator.hpp

Fixed airspeed scaling

---

EKF/ekf.h
attitude_fw/ecl_pitch_controller.h
attitude_fw/ecl_roll_controller.h
attitude_fw/ecl_wheel_controller.h
attitude_fw/ecl_yaw_controller.h

Simply add the `override` specifier whenever possible.

ekf: Add override specifiers

---

CMakeLists.txt

Only inlcude gtest if standalone build

---

EKF/ekf_helper.cpp

@jkflying Thank you for catching this.

Revert if statement swap in resetMagHeading

---

CMakeLists.txt
EKF/airspeed_fusion.cpp
EKF/control.cpp
EKF/covariance.cpp
EKF/drag_fusion.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/gps_checks.cpp
EKF/gps_yaw_fusion.cpp
EKF/mag_fusion.cpp
EKF/optflow_fusion.cpp
EKF/sideslip_fusion.cpp
EKF/terrain_estimator.cpp
EKF/vel_pos_fusion.cpp

This PR contains 8 different clean-ups each described in the commit message.
I recommend to review this commit by commit.
And it saves 450 Bytes of flash.
SITL Mission test with strange behavior: [Here](https://review.px4.io/plot_app?log=c8dc5c5d-b29b-48a8-b074-9a04aa7d8097) (SOLVED)
https://github.com/PX4/Matrix/pull/117 is solving the issue. New SITL Mission test [log](https://review.px4.io/plot_app?log=92f091db-0a76-4193-ae74-70e924a78bdf)

Random cleanup 2

---

tecs/tecs.cpp
tecs/tecs.h

https://github.com/PX4/Firmware/pull/13527#issuecomment-557354415

TECS: remove height rate complementary filter

---

validation/data_validator_group.cpp
validation/data_validator_group.h

Needed for
https://github.com/PX4/Firmware/pull/12989

data_validator_group: add a method to get the state of the sensor

---

test/test_EKF_ringbuffer.cpp

Stumbeled on this by chance :wink:

EKF_ringbuffer: minor missing space for style

---

.github/workflows/build_tests.yml
.github/workflows/firmware_build_test.yml
.github/workflows/unit_tests.yml

**Testing:** On this PR the tests are running, but not on this: https://github.com/PX4/ecl/pull/725

Run github actions also on PRs from forks

---

CONTRIBUTING.md

This is a first draft of the contribution guidelines. I am sure I missed a lot of things. Feel free to raising missing parts or even add them on top.
This PR counts on https://github.com/PX4/ecl/pull/727 xD

First draft of the contribution guidelines

---

.clang-format
EKF/RingBuffer.h
EKF/imu_down_sampler.cpp
EKF/imu_down_sampler.hpp
EKF/vel_pos_fusion.cpp
mathlib/mathlib.cpp
mathlib/mathlib.h
tools/format.sh
validation/data_validator.cpp
validation/data_validator.h
validation/data_validator_group.cpp
validation/data_validator_group.h

Expanding auto-formatting to folders `mathlib` and `validation` and files `EKF/vel_pos_fusion.cpp` and `imu_down_sampler.*pp`
Style changes: 
- Increase penalty on breaking line after an assignment
- Add opening brackets for functions on new line.

Expanding auto-formatting

---

EKF/control.cpp

Fix to bug introduced in https://github.com/PX4/ecl/pull/729

Hot flow fusion fix

---

EKF/imu_down_sampler.cpp
EKF/imu_down_sampler.hpp

- minor formatting and initialization cleanup

EKF: ImuDownSampler pass imuSample as const reference

---

EKF/ekf.h

- PX4 astyle puts the reference with the name.

EKF: covariances() helper return const reference and fix code style

---

EKF/control.cpp

I was going to take a look at aiding range aid for vision height mode, but thought I'd get this out of the way first.

EKF control minor cleanup (use switch statement and fix code style)

---

EKF/EKFGSF_yaw.cpp
EKF/EKFGSF_yaw.h
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h

@priseborough Could you please test if this is still working on the replay logs? And I noticed that we never properly align the tilt of the [AHRS](https://github.com/PX4/ecl/blob/master/EKF/EKFGSF_yaw.cpp#L238)
@bresch The change indication file changed on my machine locally without any changes to the code.

CleanUp of the EKFGSF

---

.github/workflows/build_tests.yml
.github/workflows/firmware_build_test.yml
.github/workflows/format_checks.yml
.github/workflows/functional_change_indicator.yml
.github/workflows/unit_tests.yml

We missed to check the change indication on open PRs.

Check change indication on PR

---

EKF/ekf_helper.cpp

Some non-functional style improvements.

Tiny cleanup

---

EKF/ekf_helper.cpp

Fixes https://github.com/PX4/ecl/issues/784.

elk_helper: use ISFINITE macro instead of isfinite()

---

EKF/EKFGSF_yaw.cpp

This simplifies the centripetal acceleration calculation and handles general 3D manoeuvres provided the X axis is pointing in the direction of  wind relative flight.
It has been tested using px4_sitl gazebo_plane. GSF, Sim and EKF yaw differences are equivalent for before and after tests indicating equivalentcentripetal accel correction.
Before:
After:

EKF: Simplify centripetal accel correction

---

EKF/control.cpp
EKF/ekf.cpp
EKF/sensor_range_finder.cpp
EKF/sensor_range_finder.hpp
test/test_SensorRangeFinder.cpp

For better distinction between sensor tiltOffset and the tilt of the drone.

Change naming from tiltOffset to pitchOffset

---

EKF/common.h
EKF/covariance.cpp
EKF/estimator_interface.cpp
EKF/imu_down_sampler.cpp
test/sensor_simulator/imu.cpp

Mainly hacks for testing at this point.
Questions:
~~1. Is it worth handling this per axis? Clipping in Z is the most common.~~
Goes with ~~https://github.com/PX4/Firmware/pull/13103~~ https://github.com/PX4/Firmware/pull/14304.

EKF increase delta velocity variance while sensor is clipping

---

EKF/common.h
EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
test/CMakeLists.txt
test/sensor_simulator/range_finder.cpp
test/sensor_simulator/range_finder.h
test/sensor_simulator/sensor_simulator.cpp
test/test_EKF_externalVision.cpp
test/test_EKF_flow.cpp

Refactor velocity reset

---

EKF/EKFGSF_yaw.cpp
EKF/EKFGSF_yaw.h
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
EKF/gps_yaw_fusion.cpp

I ran a static analysis using `cppcheck --enable=style` and found a few things to fix.

Random cleanup

---

test/sensor_simulator/ekf_wrapper.cpp
test/sensor_simulator/ekf_wrapper.h
test/test_EKF_initialization.cpp

Unit test added for https://github.com/PX4/ecl/pull/818
See https://github.com/PX4/ecl/pull/818#issuecomment-630847839

unit test: check that the accel bias is only learned when observable

---

tecs/tecs.cpp
tecs/tecs.h

tecs: fix typo init(i)alized

---

EKF/common.h
EKF/ekf.h
EKF/estimator_interface.h
EKF/terrain_estimator.cpp

A PR in Firmware will follow this to actually log the bitmask

Terrain estimate: Added height above ground source bitmask

---

.clang-format
EKF/RingBuffer.h
EKF/imu_down_sampler.cpp
EKF/imu_down_sampler.hpp
EKF/vel_pos_fusion.cpp
mathlib/mathlib.h

- this keeps things mostly consistent with PX4/Firmware formatting

clang-format set BreakBeforeBraces to Linux style

---

EKF/airspeed_fusion.cpp
EKF/drag_fusion.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
EKF/gps_yaw_fusion.cpp
EKF/mag_fusion.cpp
EKF/optflow_fusion.cpp
EKF/sideslip_fusion.cpp
EKF/terrain_estimator.cpp
EKF/vel_pos_fusion.cpp

This PR contains multiple non functional improvements. It can easily be reviewed commit by commit.

Big random cleanup

---

EKF/ekf.h
EKF/ekf_helper.cpp

fixes https://github.com/PX4/ecl/issues/824

Return type of resets

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp

Refactoring this out increases readability.

Refactor ev fusion start into helper functions

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp

Tiny refactor of gps fusion start into separate function

Tiny refactor of gps fusion start

---

geo/geo.cpp
test/test_geo.cpp

This is probably why the MAVSDK test is failing.

Geo: Fix double correcting for negative distance

---

EKF/airspeed_fusion.cpp
EKF/drag_fusion.cpp
EKF/ekf.h
EKF/gps_yaw_fusion.cpp
EKF/mag_fusion.cpp
EKF/optflow_fusion.cpp
EKF/sideslip_fusion.cpp
EKF/vel_pos_fusion.cpp

This adds a generic function for the measurement update. Best to review commit by commit.

Generic measurementUpdate function

---

EKF/EKFGSF_yaw.cpp
EKF/airspeed_fusion.cpp
EKF/covariance.cpp
EKF/ekf.cpp
EKF/ekf_helper.cpp
EKF/mag_fusion.cpp

There was some issue with reusing a branch with the same name.

Random cleanup 3

---

ecl.h

- ECL_{INFO,WARN,DEBUG} add newline
- ECL_{INFO,WARN,DEBUG}_TIMESTAMPED add imu timestamp and newline

ECL standalone build improve ECL_INFO/WARN/DEBUG

---

EKF/control.cpp
EKF/ekf.h
EKF/mag_control.cpp

Looking towards not having to store things like `_mag_data_ready` and `_mag_sample_delayed`

EKF: update mag LPF immediately

---

test/sensor_simulator/ekf_wrapper.cpp
test/sensor_simulator/ekf_wrapper.h
test/test_EKF_flow.cpp

flow: add unit test for yaw motion

---

test/test_SensorRangeFinder.cpp

fixes https://github.com/PX4/PX4-Autopilot/issues/16480

Rng finder unit test: cover "un-stuck" logic

---

EKF/EKFGSF_yaw.cpp
EKF/EKFGSF_yaw.h

The code this PR removes was added for use during the development, and is no longer required.

EKF: Remove dead code

---

EKF/ekf_helper.cpp

So we can explicitly handle the uninitialized case in the estimator selector.
In some situations the test ratios can get very close to zero, which is what the estimator selector currently uses to consider these test ratios uninitialized.
https://github.com/PX4/PX4-Autopilot/pull/17805#issuecomment-870637215

EKF: set uninitialized vel/pos/hgt test ratios to NAN

---

EKF/drag_fusion.cpp

Addresses https://github.com/PX4/PX4-Autopilot/pull/17791#issuecomment-866195098

EKF: Fix clang-tidy complaint

---

.github/workflows/build_tests.yml
.github/workflows/firmware_build_test.yml
.github/workflows/format_checks.yml
.github/workflows/functional_change_indicator.yml
.github/workflows/unit_tests.yml
.github/workflows/update_change_indicator.yml

Use same version as PX4-Autopilot

CI: update container version
