PX4/PX4-ECL

EKF/ekf_helper.cpp

std::to_string is not supported in the Hexagon complier
Signed-off-by: Mark Charlebois <charlebm@gmail.com>

Added hexagon support

---

EKF/ekf.cpp
EKF/estimator_base.cpp

the delta angle bias was applied to imu data which was not coming in the same
time intervall as the filter was operating. Therefore, the delta angle bias
applied to new imu data had to be scaled correctly in order to match
the imu time interval.

fix delta angle bias usage:

---

EKF/RingBuffer.h
EKF/estimator_base.cpp

Must use PRIu64 for printf of uint64_t to prevent compiler errors.
Signed-off-by: Mark Charlebois <charlebm@gmail.com>

Fixed printf of uint64_t

---

EKF/ekf.cpp
EKF/ekf.h
EKF/estimator_base.h
EKF/mag_fusion.cpp

Modifies the magnetometer 3-axis fusion so that the 3 components are fused on the one time step. This is necessary because all three components need to pass innovation consistency checks before sequential fusion is performed. This means the magnetometer fusion is no longer spread out across three time steps which improves numerical stability, but increases timing jitter.
Adds a fusion gate parameter for the 3-axis fusion and fixes a scaling error on the exisiting heading fusion gate.
Adds a numerical error check to the 3-axis fusion innovation variance calculations.
Indoor flight test with3-axis fusion here: http://logs.uaventure.com/view/qwawJmkkUMbKJWm3uttDzc
Magnetomter innovation plots (note innovation offsets at start and end of flight when taking off and landing on the steel …

EKF: Add magnetometer fusion error handling

---

EKF/common.h
EKF/covariance.cpp
EKF/ekf.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/gps_checks.cpp
EKF/mag_fusion.cpp
EKF/vel_pos_fusion.cpp

- The tuning parameter defaults have been changed to a conservative set to handle larger magnetometer and IMU errors. This is an equivalent tune to the APM copter defaults and prioritises robustness to sensor error over accuracy. A tuning activity to obtain a 'performance' oriented tune will be performed later when the replay functionality is available in master.
- An error in in conversion from observation noise to observation variance in pos vel  fusion has been fixed.
- Velocity observation noise adapts with reported GPS speed accuracy.
- A separate position observation noise is used in-flight for operation without aiding. This reduces attitude errors due to manoeuvres.
- The missing magnetometer observation noise parameter has been added.
Flight testing has been completed (see …

EKF Tuning Update

---

EKF/common.h
EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/mag_fusion.cpp
matlab/generated/Inertial Nav EKF/Magnetic Declination Fusion.txt

This PP adds a method to fuse the declination which allows 3-axis fusion of magnetometer measurements to be used when there are no external measurements to make the heading and declination observable. It has been flight tested with and without GPS aiding.
Magnetometer fusion results with GPs aiding - note the published declination value at the test location is 11.5 deg
Magnetometer fusion results without  GPS aiding. The estimated declination stays around the parameter value of 0 deg, but the magnetometer bias offsets are still learned

EKF2: Prevent declination/heading drift during non-GPS operation

---

EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/gps_checks.cpp
EKF/vel_pos_fusion.cpp

The baro is averaged during alignment and an offset calculated that is used subsequently to ensure that the reported height of the EKF origin is correct, even for in-air GPs gain and that the filter correctly reports both absolute and relative height.
Some additional averaging is used during initialisation of the states to improve accuracy.

Correct for sensor noise and baro offset during alignment

---

EKF/common.h
EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/mag_fusion.cpp
matlab/generated/Inertial Nav EKF/Simple Magnetometer Fusion.txt
matlab/generated/Inertial Nav EKF/Yaw Angle Fusion.txt
matlab/scripts/Inertial Nav EKF/GenerateNavFilterEquations.m

This fixes a bug introduced when the heading observation jacobian and Kalman gain calculations were updated to not use magnetic field measurements directly, but the patch updating the innovation calculation had  been omitted. 
There has been further optimisation of the direct heading fusion calculations and an error in the innovation calculation for that method has ben fixed.
During testing it was noted that the direct heading angle fusion was not suitable for tail-sitter type vehicles or for other applications with arbitrary startup orientations due to poor accuracy around +- 90 degrees pitch. As a result a revised magnetometer fusion method has been developed and implemented which uses the azimuth angle of the projected magnetic field onto the horizontal as the observation. This avoids …

Fix bug in magnetic heading fusion

---

EKF/common.h
EKF/control.cpp
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/geo.cpp
EKF/geo.h
EKF/mathlib.h
EKF/vel_pos_fusion.cpp

The magnetic field states and yaw angles were being reset on transition into GPS mode, not 3D fusion mode. 
This could cause large magnetometer innovations and upsets in roll and pitch when 3D fusion commenced if the vehicle was subject to significant field disturbances on the ground when it started using GPS.
This PR ensures that the mag field states and yaw are always reset when entering 3D fusion mode, and that the angle error covariances are zeroed to prevent unwanted angle disturbances when commencing 3D fusion.
The following flight test data shows an in-air transition into 3D fusion. Note that the angle error variances quickly recover within seconds of the reset due to the imu process noise.

EKF: Fix Bug Causing Roll/pitch Disturbances On Mag Fusion Mode Switch

---

EKF/ekf_helper.cpp

When doing a test flight in the lab with the Pixracer using latest ecl master the quad suddenly twitched some seconds after it was in the air. The log showed that the attitude jumped considerable (see picture below). This jump occurred when the heading reset happened (switch from heading fusion to 3D mag fusion). I believe that the problem was that we were setting the output attitude equal to the yaw corrected ekf attitude which is of course delayed and thus now necessarily a good choice.

Attitude reset after heading reset

---

EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/gps_checks.cpp
EKF/vel_pos_fusion.cpp

Use GPS reported accuracy to set position observation noise, but bound the noise to safe limits set by the parameters. This reduces the effect of noisy GPS on filter estimates
Publish the filter absolute position uncertainty in the horizontal and vertical directions and indicate if the filter is dead reckoning. This reporting takes account of uncertainty in the EKF origin. This information can be combined with GPS error reporting outside of the filter to make better decisions based on control loop accuracy requirements.
It has been flight tested in an indoor environment with noisy GPS. http://logs.uaventure.com/view/y93HLUxKJtzsPwpzZYrZMP
Test result show that the innovation variance is adjusting to the variations in GPS accuracy

EKF: Improve Position Accuracy Reporting

---

EKF/ekf.cpp

Hi there,
There were a few additional variable re-initializations required in order to get everything restarted without NaN's if the filter happens to diverge.

Additional filter variable initializations required to fully reset the filter variables

---

EKF/common.h
EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/mag_fusion.cpp
matlab/generated/Inertial Nav EKF/Yaw Angle Fusion.txt
matlab/scripts/Inertial Nav EKF/GenerateNavFilterEquations.m

**Information**
Replaces #67 
The previous default method of fusing magnetometer data when on the ground used the azimuth angle of the projection of the measured field onto the horizontal. Unfortunately this method did not decouple the observation from the roll and pitch angle in the filter observation equations with the result that magnetic field interference could create large errors in the estimated roll and pitch.
The alternative provided as an option was fusion of the Euler yaw angle obtained from a separate magnetic compass calculation which had much smaller levels of roll and pitch error due to magnetic field disturbances. However this could not be used as a default method because it suffered from singularities at +-90 deg pitch.
The solution was to enable fusion of magnetic …

EKF: Reduce effect of magnetic field disturbances on roll and pitch

---

EKF/control.cpp

This enables the use of the PX4 landing detector to get information if the vehicle is in the ground or not. This feature is only available if we are using gps.

use in_air flag from landing detector

---

EKF/ekf.h
EKF/mag_fusion.cpp

This also moves the large 24x24 arrays to static memory as they are used by all fusion processes.
TODO - move covariance updates for all fusion processes into a function that uses a mask to indicate when elements in the observation Jacobian are to be used.

Fix bug in declination fusion and standardise covariance update

---

EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/gps_checks.cpp
EKF/terrain_estimator.cpp
EKF/vel_pos_fusion.cpp

These changes allow the range finder to be used as the primary height source for operation over flat surfaces with protection for intermittent range finder  measurements during all phases of operation and allows use of baro height if the range finder measurements are lost in flight. If range finder measurements are lost on-ground, then an assumed ground clearance value set by EKF2_MIN_RNG will be used.
Note: If the range finder has been specified as the primary height reference, the filter will not initialise until 10 valid range finder measurements have been received. 
This mode can be tested by setting EKF2_HGT_MODE parameter to 2.
The following innovation and height estimate plots are from indoor testing with intermittent range finder measurements when the vehicle was on the ground.

EKF: Fix bugs preventing use of range finder as primary height source

---

EKF/common.h
EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/gps_checks.cpp
EKF/mag_fusion.cpp
EKF/vel_pos_fusion.cpp

- Add GPS accuracy data to GPS buffer so that the accuracy and measurement information used by various processes is from the same point in time.
- Define maximum measurement intervals for different sensor types so that timeouts can be detected using consistent thresholds
- Use a combined time and height uncertainty criteria to determine if the height state needs to be reset
- Maintain a filtered baro height correction so that the baro data can be used as a fall-back if either range or GPS height fusion fails
- Use  low pass filtered data during alignment instead of averaged data to reduce the effect of time delays and allow for longer averaging periods when using range finder data.
- Implement a consistent fall-back behaviour following a height fusion timeout.
**Flight Test Results** …

EKF: Add option to use GPS for height and improve height fall-back behaviour

---

EKF/control.cpp
EKF/ekf_helper.cpp

Addresses https://github.com/PX4/ecl/issues/91
If bad inertial data causes a large vertical velocity, resetting the height without also resetting the vertical velocity is ineffective, because the bad velocity will pull the height away from the measurement resulting in repeating height resets.
This PR adds code to reset the vertical velocity to the GPS if available, following a vertical position reset.
The variances for the vertical position and velocity states are also reset using known sensor error characteristics.

EKF: Fix vulnerability in height reset

---

EKF/common.h
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/mag_fusion.cpp
EKF/optflow_fusion.cpp
EKF/terrain_estimator.cpp
EKF/vel_pos_fusion.cpp

Has been test flown with offsets set for optical flow, range finder and GPS in GPS only and optical flow only modes. Needs a means of setting sensor positions in the simulator.
Needs https://github.com/PX4/Firmware/pull/4227 to work
Here are the optical flow only test results:
http://logs.uaventure.com/view/48Rr2JT8z422asCx4rqAfJ

Add compensation for EKF sensor position offsets

---

matlab/analysis/estimatorLogViewerPX4.m
matlab/analysis/importPX4log.m

Modifies the log importer to ingest both .px4log and .bin files (handles the STRT message, doesn't require the TIME message, if TIME message present uses a fieldname that is overloaded)
Updates viewer to handle the new timestamp fieldname, which makes the viewer PX4 specific (it assumes the population of that field, which in turn requires the TIME field).

Matlab log import

---

EKF/RingBuffer.h
EKF/common.h
EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h

Addresses #96 and #91 
Has been flown in SITL for normal operation and bench tested for a GPS height timeout
Height reset recovery from each of the three modes (Baro, GPS and range finder) needs to by tested. I have tried using SITL, but it does not support adding offsets to sensor outputs.

EKF: Improve height reset behaviour

---

EKF/ekf.cpp

The previous solution did not work for Snapdragon, so I needed to copy
what is used in px4_defines.h.

ekf: another stab at fixing isfinite for all

---

EKF/ekf.cpp

This fixes an access to an uninitialized value.
in PX4 Firmware: Ekf::get_terrain_vert_pos depends on it. This is the valgrind output:
```
==15439== Thread 14 ekf2:
==15439== Conditional jump or move depends on uninitialised value(s)
==15439==    at 0x5610087: sqrtf (in /usr/lib64/libm-2.22.so)
==15439==    by 0x4D1AF0: Ekf::get_terrain_vert_pos(float*) (terrain_estimator.cpp:135)
==15439==    by 0x46641F: Ekf2::task_main() (ekf2_main.cpp:655)
==15439==    by 0x42BF3D: entry_adapter(void*) (px4_posix_tasks.cpp:103)
==15439==    by 0x4E3C609: start_thread (in /usr/lib64/libpthread-2.22.so)
==15439==    by 0x5BF7A4C: clone (in /usr/lib64/libc-2.22.so)
```

ekf: initialize _terrain_var

---

EKF/common.h
EKF/ekf.cpp
EKF/ekf.h

Enables smaller output complementary filer time constants to be used for position and velocity states in response to https://github.com/PX4/ecl/issues/125. 
Replace the delayed time feedback mechanism used by the translational states with a direct feedback method.
Time constants for velocity and position convergence can be separately adjusted with tunable parameters.
The method is more computationally more expensive because it requires modification of the output buffer history but is acceptable because updating the buffer only requires 6 FLOP per buffer index for a total of 30*6 = 180 FLOP per output update. EKF2 processing utilistion on a Pixracer board has going up from 15.1 to 15.7 % as a result of this change. These changes may not be necessary if the issues associated with the …

EKF:  Improve output observer position and velocity tracking

---

EKF/ekf.cpp
EKF/estimator_interface.cpp

added ev_pos flag check to valid_lpos check.
need to disable fake gps when ev_pos is valid, not just optical flow.

EV testing

---

EKF/RingBuffer.h
EKF/ekf.cpp

This PR introduces an optional method of predicting the velocity forward from the fusion to the output time horizon. It is activated by setting EKF2_TAU_VEL to a negative value. This causes the state history for the output predictor states to be corrected using the position difference instead of the velocity difference. The end result is a velocity that more closely matches the first derivative of the position. This may help in situations where control loops rely on kinematic consistency between position and velocity.
Tested with https://github.com/PX4/Firmware/tree/pr-ekf2OutputPredictor and EKF2_TAU_VEL = -1
Flight test log here: http://logs.uaventure.com/view/C5gVya4qXoKuHXPXEY5AxJ
Plots of the vertical position and velocity for the EKF and predictor:

EKF2 provide alternative output velocity prediction

---

EKF/estimator_interface.cpp
EKF/estimator_interface.h

The protection against high data rates causing data to be overwritten in the buffers before it could be fused was inconsistent between different observation types and missing for EV data. This PR implements a consistent method of limiting the data rate and removes unnecessary function calls and functions.
Removes unnecessary function calls
Removes un-used functions
Applies a consistent maximum safe data rate check for all observation inputs
Test flight here:
http://logs.uaventure.com/view/Wuy2cSbtvLNafrvreFXvp3

EKF: Fix vulnerability to loss of observations due to high input data rates

---

EKF/common.h
EKF/control.cpp
EKF/ekf.cpp
EKF/ekf_helper.cpp
EKF/vel_pos_fusion.cpp

Addresses: #141 and #151. Note turning accel bias learning off via the EKF2_AID_MASK parameter may still be beneficial depending on tuning for external vision operation with accurate sensing.
Required for https://github.com/PX4/Firmware/pull/4647
Replayed log fusing external vision data here (experimental data courtesy of @pickledgator from #141)
http://logs.uaventure.com/view/eZryf2znyV9stqokLeWkwj
Replayed log fusing external vision and range finder data here (experimental data courtesy of @pickledgator from #141)
http://logs.uaventure.com/view/aGBegC39R5Rdx33GazzuvF
EKF plots from second log
log from normal quad flight with GPS here:
http://logs.uaventure.com/view/a5JUpD5uXC9thJV9kD6KRK

EKF: external vision bug fixes

---

EKF/ekf.cpp

Wait a full buffer cycle before using data to set initial alignment value.
Flight log here: http://logs.uaventure.com/view/B2zyHuGF8AX8yG5KteUtEi

EKF: Ensure bad initial data is flushed from buffers before use

---

EKF/airspeed_fusion.cpp
EKF/common.h
EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/mag_fusion.cpp
EKF/optflow_fusion.cpp
EKF/terrain_estimator.cpp
EKF/vel_pos_fusion.cpp

Position and velocity state reset deltas and times are captured and are published. This data allows control loops to compensate for resets via set-point changes if required.
Innovation consistency check failures are captured and published as an integer bit-mask. This data in combination with the innovations and innovation variances will assist with monitoring sensor health.
Indoor flight test with GPS using a pixracer board
http://logs.uaventure.com/view/XWF2ovMGg4sr2mKexoGd9c

EKF: Publish full reset and innovation consistency check status data

---

EKF/control.cpp
EKF/estimator_interface.cpp
EKF/gps_checks.cpp
ecl.h

- Changes all printfs to ECL printfs
- Add ECL_ERR.
- Include ecl.h where needed.
- Add forgotten pragma once.

EKF: use ECL printfs everywhere

---

EKF/airspeed_fusion.cpp
EKF/covariance.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/mag_fusion.cpp

Fixes a big in the quaternion covariance reset function that resulted in an inaccurate covariance matrix which resulted in replay of this log producing a badly conditioned magnetometer fusion calculation which triggered a full covariance reset 
http://logs.uaventure.com/view/xmv7Eb4ss29vmFPMHSfiEH
- Fixes a bug that bypassed the innovation consistency protection for 3-axis magnetometer fusion.
- Cleanup of 3D mag fusion auto-code and reduction in memory requirements
- Removes an approximation in the calculation of the magnetometer innovation variance for improved accuracy.
- If a full covariance reset is performed, the wind and magnetic field state variances are given 'reasonable' starting values.
- Introduces a partial covariance reset where only the covariance terms used by the …

EKF: Fix critical bugs in mag fusion and yaw reset

---

EKF/ekf.cpp

This makes it possible to activate airspeed fusion by setting a parameter, it is however off by default for the moment.
Goes together with https://github.com/PX4/Firmware/pull/4755

activate tas fusion, off by default

---

EKF/ekf.h
EKF/estimator_interface.h

@priseborough I changed the reset interface slightly so that there are no vector dependencies. Also this allows us to copy the reset data directly into the topic structs.

Change state reset information interface

---

EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/optflow_fusion.cpp

This PR moves the checking for sensor data and control of data use out of the Ekf::update() program and into separate functions for each sensor type. This means that decisions requiring data are only made when there is data available for that sensor.
Reset functions for velocity and position have been simplified to take advantage of only being called when there is updated sensor data available .
Notification to the console has been improved.
Function naming has been improved.
A potential div0 bug has been fixed
**Testing Status**
Flight and replay tested GPS, baro and magnetometer fusion operation. Unable to complete testing of other fusion types.

EKF: clean up fusion control logic

---

EKF/RingBuffer.h
EKF/estimator_interface.cpp

__STDC_FORMAT_MACROS changes the behavior of inttypes.h to allow
defining format macros for printf-like functions. It needs to be defined
before any include is done, otherwise due to include chains and header
guards it may not take effect.
Instead of defining it everywhere it is used, let the PX4 build system
to deal with it.

Move __STDC_FORMAT_MACROS to build system

---

EKF/ekf_helper.cpp

This fixes a compile error with GCC 5.2.0 and cross-compilation:
/usr/arm-none-eabi/include/c++/5.2.0/arm-none-eabi/armv7e-m/fpu/bits/error_constants.h:122:27: error: 'ENOTSUP' was not declared in this scope
not_supported =     ENOTSUP,
The problem was that the #include <iomanip> was taken from the host system,
which conflicts with includes from NuttX (NuttX has only basic C++ STL
support)

ekf_helper.cpp: remove unused includes

---

CMakeLists.txt
EKF/ekf_helper.cpp
EKF/tests/base/CMakeLists.txt
EKF/tests/ringbuffer/CMakeLists.txt

This removes the optimization flag (optimize for size) out of the module because it should be taken care of on a platform level rather than a module level.

Remove optimization flags

---

EKF/common.h
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h

**DESCRIPTION**
Add integral action to the output predictor position and velocity tracking to reduce the effect of acceleration aliasing and bias errors.
Publish the tracking errors to assist with diagnostics and tuning.
Retune the time constant used to track the velocity states.
**TEST DATA**
Plot of attitude (EST4.e1), velocity (EST4.e2) and position (EST4.e3) tracking error magnitude from a flight test with a Pixracer board. Units are rad, m/s and m respectively.
A corresponding PR has been raised on PX4/Firmware to enable data logging: https://github.com/PX4/Firmware/pull/5318
Back to back comparison tracking data using the tracking loops before and after the change applied to a replay log with high vibration levels (wingwing flight vehicle with pixracer board). There is some …

EKF: Improve Output Predictor Tracking

---

EKF/ekf.cpp
EKF/terrain_estimator.cpp

- assign the flag storing the initialization state of the terrain estimator to the output of the init function in the ekf main init function. The estimator was initializing twice before.
- when initializing the terrain estimator use the projection of the range measurement rather than the raw value. Also do not allow initialization if the vehicle is tilted too much.

Pr hagl init

---

EKF/common.h
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/terrain_estimator.cpp

Publishes data required for the mavlink ESTIMATOR_STATUS message to be fully populated. Is required for https://github.com/PX4/Firmware/pull/5610.

EKF: Publish missing data required for MAVLINK ESTIMATOR_STATUS message

---

EKF/mag_fusion.cpp

This fixes the bug that causes the mag_test_ratio message in the mavlink estimator_status report to have a floor set by the last value of the heading fusion test value.

EKF: Fix magnetometer innovation test ratio reporting bug

---

EKF/control.cpp
EKF/ekf_helper.cpp

- position reset method was returning before the actual delta values
were written and applied to the output buffer
- apply reset delta also to the output sample which was already taken out
from the output buffer, otherwise the complementary filter solution is
offset from the ekf solution

proper handling of position and velocity reset

---

EKF/ekf_helper.cpp

This slipped through from my last PR.
The height delta from the reset was applied twice to the newest height state.

ekf2 height reset

---

EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h

Add calculation and reporting of IMU delta angle and velocity coning and high frequency vibration.
These will need to be published on the estimator_status uORB message which is currently un-used.
This has been flight tested and the messages checked using this branch: https://github.com/PX4/Firmware/pull/5682

EKF: Add IMU vibration calculation and reporting

---

EKF/common.h
EKF/control.cpp

- if both gps position and velocity measurements are rejected for 7 seconds
do a reset
- if only gps position measurements are rejected then wait for 14 seconds
as we still have velocity measurements to constrain the drift in position
- introduced ecl internal parameter for the timeout

ekf reset: more granular reset / timeout strategy for gps fusion

---

EKF/airspeed_fusion.cpp
EKF/ekf.h
EKF/mag_fusion.cpp
EKF/optflow_fusion.cpp
EKF/vel_pos_fusion.cpp
validation/data_validator.cpp
validation/data_validator.h
validation/data_validator_group.cpp
validation/data_validator_group.h

Save memory by moving the KHP matrix to the stack and using a smaller timeout data type in DataValidator.
@priseborough @tumbili can you please review?

Save memory

---

EKF/control.cpp

This bug could cause eventual loss of attitude reference when operating without GPS connected.

EKF: Fix bug causing repeated resets if GPS sensor disconnected

---

EKF/common.h
EKF/ekf.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h

Saves RAM and reduces output predictor errors by using the smallest data buffer length that meets time delay and update rate requirements. Buffer sizes used are sent to ground via ECL info message to enable verification and testing with default parameters has verified the correct IMU buffer size of 21 and observation buffer size of 11.
Replay flight log here (used https://github.com/PX4/Firmware/pull/5814): http://logs.uaventure.com/view/ULJNmyuTUe9SjAfkh6e3jG
Replay log result  here (used https://github.com/PX4/Firmware/pull/5814):  http://logs.uaventure.com/view/yN5xVF9K6CoNhFDPefK2zk

EKF:  Reduce RAM usage and output predictor errors

---

EKF/control.cpp

Fixes a bug that allows air data fusion to start when the filter is still assuming constant position.
Fixes a bug that prevents a position reset happening immediately if GPS is gained and passes checks when already using optical flow.

EKF minor bug fixes

---

attitude_fw/ecl_pitch_controller.cpp

@LorenzMeier this needs to get in before the next stable PX4. This commit is on top of the version of ecl in PX4 beta, so src/lib/ecl in beta could be reset to this branch (hotfix_ecl_pitch) if needed.
I've flown the current broken version in SITL/HIL/IRL multiple times, and only noticed the error in bench testing.

fw att fix pitch feedforward constrained roll

---

EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h

This is required to support PX4 Firmware fixes for https://github.com/PX4/Firmware/issues/6193. The origin is not valid until it has been fixed and the EKF is using it as a reference.

EKF: Add validity flag to ekf origin reporting

---

EKF/control.cpp
EKF/estimator_interface.cpp

Partially addresses https://github.com/PX4/Firmware/issues/6347
1) Enables takeoff in position control mode when the OF sensor is out of focus and quality metric fails acceptance test by setting flow measurements to a value equivalent to zero horizontal velocity.
2) If optical flow is lost and then resumed in flight and there is no other means of determining position (eg GPS), the position will be set to the last known position when optical flow was lost.
Because I am running OSX Sierra, I have been unable to test the proposed ecl EKF changes using the gazebo sim as the gazebo installer is incompatible with my OS version.

EKF: optical flow improvements

---

EKF/common.h
EKF/covariance.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h

**Fixes**
Flight at high angular rate and vibration levels in a multi-rotor was able to cause the IMU delta velocity bias values to be learned incorrectly. This created an offset in the vertical velocity that prevented the vehicle from completing a landing.
**Description of changes**
A bad delta velocity bias evidenced by baro and GPS vertical velocity innovations having the same sign and a bias value over 90% of the maximum for a continuous period will cause the covariance matrix entries for accel bias values to be reset.
The downsampling from the 4msec IMU to 10msec EKF covariance prediction time step has been changed so that the EKF now uses 12 msec as the target time and the downsampling algorithm has been modified so that the jitter in EKF prediction time step is greatly reduced. …

EKF: protect accel bias learning from high manoeuvre and vibration levels

---

EKF/estimator_interface.cpp

This fixes a bug that allows the EKF to try using GPS data when there is no longer a 3D fix. This prevents the timeout reversion back to non-GPS operation that is supposed to occur after 10 seconds of no GPS lock

EKF: don't accept GPS data without a 3D lock

---

EKF/ekf_helper.cpp

This change removes the following compiler error when building using the ARM cross compiler.
/Users/paul/src/Firmware/src/lib/ecl/EKF/ekf_helper.cpp:45:12: error: 'std::abs' has not been declared
using std::abs;

EKF: improve compatibility with ARM cross compiler

---

EKF/common.h
EKF/control.cpp
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h

These changes mean that if complete rejection of all aiding data occurs, a conservative estimate of position error will be reported which is the greater of the error estimate obtained from the state variances and the error estimate obtained from the innovations.
This will enable improvements to failsafe logic in the controllers.
It has been tested in SITL by setting = EKF2_MAG_DECL to 90 degrees which causes GPS measurements to be rejected shortly after takeoff. See following plot of the eph reported by the local and global position topics from this test.

EKF: Improve position error reporting

---

EKF/covariance.cpp
EKF/estimator_interface.cpp
EKF/gps_checks.cpp

This fixes a bug where movement of the vehicle during alignment can cause the bad accel bias condition to latch to true which will cause the solution status to report incorrectly.

EKF: fix bugs preventing preflight checks passing

---

EKF/gps_checks.cpp

This fixes a bug that was introduced when GPS checks were enabled to run whenever the vehicle was on the ground by this PR https://github.com/PX4/ecl/pull/255 . This resulted in the EKF origin being continually being updated to match the GPS position when on ground.
Doing this can cause large jumps in GPS position and generate innovation check errors after landing and also reduces the usefulness of pre-flight GPs position innovation consistency checks.
Moving the origin is unnecessary because the origin is already performed here https://github.com/PX4/ecl/blob/master/EKF/gps_checks.cpp#L68  after all enabled GPS checks have passed.

EKF: Do not move EKF origin when performing GPS checks

---

EKF/covariance.cpp
EKF/ekf.cpp
EKF/ekf.h

The previous practice of relying on the off-diagonals being zero and maintaining the diagonals (variances) caused problems with conditioning of the covariance matrix on one flight. This can result in the magnetometer fusion failing the numerical health test and the covariances being reset in mid flight.
This change stores the variances when the learning inhibit becomes active and ensures that the rows and columns in the covariance matrix for the inhibited states are explicitly maintained at zero. When the delta velocity bias learning inhibit is released the variances are re-instated.
It also protects the covariance prediction from excessively small or large delta time values that could poor numerical conditioning.
During replay of a problem flight log, this eliminated the in-air …

EKF: Protect against covariance prediction and update errors

---

EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/gps_checks.cpp

The GPS drift calculations need to be able to run independently of the EKF origin. This PR uses separate variables for the GPS drift calculation so that the EKF origin is not modified after GPS checks have passed and the vehicle is on-ground.
It also fixes the bug that was effectively bypassing the horizontal GPS drift check.

EKF: Don't use EKF origin in GPS drift check calculation

---

EKF/common.h
EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp

This PR uses vertical velocity and position innovation consistency check failure to detect bad accelerometer data caused by clipping or aliasing which can cause large vertical acceleration errors and loss of height estimation. When bad accel data is detected it
1) Reports bad accel status using bit position 11 in the estimator solution status message.
2) Forces fusion of vertical velocity and height data by bypassing innovation consistency checks to reduce the vertical velocity and position error.
3) Inhibits accelerometer bias learning to prevent accel bias estimates being corrupted by forced fusion.
4) Increases accelerometer process noise to reduce effect of bad accel data on state estimates.
**Testing**
Testing on replay logs from vehicle with significant vibration induced clipping …

EKF: improve recovery from bad IMU accel data

---

CMakeLists.txt
EKF/CMakeLists.txt
EKF/common.h
EKF/control.cpp
EKF/covariance.cpp
EKF/drag_fusion.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/optflow_fusion.cpp

This PR implements the fusion method derived here: https://github.com/PX4/ecl/blob/master/matlab/scripts/Inertial%20Nav%20EKF/GenerateNavFilterEquations.m#L425
It enables the drag of a multi-rotor measured perpendicular to the thrust axis to be used to form aa rough estimate of wind velocity. It has been tested on replay and flight test.
Here are the XY acceleration innovations and wind velocity estimates from a flight test with around 5m/s wind swinging between SW SSW.
XY drag accel innovations
Vehicle and Wind Velocity
At 535 and 565 seconds, the vehicle was allowed to drift downwind in attitude control mode to provide a check on wind drift. The vehicle speed asymptotically approaches the wind speed estimate and the direction of drift is within 25 deg of the wind direction.

Add wind estimation for multi-rotors

---

EKF/estimator_interface.cpp

Use the equivalent single precision function

EKF: remove clang build error message

---

EKF/common.h
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h

Found during SITL Valgrind usage.
Valgrind was unhappy about quite a few different fields in EKF2, so it was ultimately easier to initialize the entire header.
I can rebase this later if it currently interferes.

ekf2 initialization fixes

---

EKF/common.h

The GPS delay has been reduced to a value that is more representative of the Ublox 7 and 8 receivers used by the majority of users. 
The airspeed delay has also been reduced to a value that better matches actual delays of pitot-static sensing after noise filtering.
These changes significantly reduce the size of the data buffers and reduce RAM utilisation.

EKF: Adjust default time delay params and clean up formatting

---

EKF/optflow_fusion.cpp

Optical flow fusion numerical errors were being written to the wrong index in _innov_check_fail_status.

EKF: fix reporting of optical flow fusion errors

---

EKF/common.h
EKF/control.cpp

These changes implement an improved method of detecting the loss of vertical estimation accuracy due to vibration induced accelerometer clipping. The statistical confidence check is not a combined check using the product of the vertical velocity and position innovations and tuneable via a single confidence parameter. The amount of failure time required to trigger a state reset is also adjustable.
This has resulted in reductions in the time required to recover from clipping. The following plots show the vertical velocity and position innovation results from replay testing of a flight log with a clipping event that starts at 622.5 seconds. 
**Before**
**After**

EKF: Increase sensitivity and add tuning of bad accel checks

---

EKF/common.h
EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp

This PR modifies the logic that us used to automatically select whether the magnetometer heading or 3-axis measurement fusion method is used. The previous logic always used the 3-axis method once the vehicle had started flying, however this can cause problems for vehicle that enter into stable position hold for extended periods immediately after takeoff.
The revised logic uses horizontal acceleration to check if yaw is observable independent of the magnetometer and uses  about the vertical to check if mag bias states are observable.
If neither yaw of mag biases are observable, it saves the magnetic field variances, the learned declination and switch to magnetic yaw fusion. When yaw or biases become observable, the saved variances are reinstated and it and switches back to 3D mag fusion. …

EKF: Prevent long periods of flight without movement causing yaw drift

---

EKF/common.h

Int seems to not be int32 on Snapdragon QuRT. Updating these fields to match the actual PARAM_TYPE_INT32 needed for BlockParam updates here https://github.com/PX4/Firmware/pull/7340

parameters use int32_t

---

EKF/RingBuffer.h
EKF/common.h
EKF/ekf.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h

This PR adds a parameter selectable option to output a more kinematically position and velocity. This will have degraded tracking relative to the EKF states, but the velocity will be closer to the first derivative of the position and reduce the effect of inertial prediction errors on control loops that are operating in a pure velocity feedback mode.
Results show that this significantly reduces steady state velocity estimation errors due to inertial sensor bias, but at the expense of an increased effect of baro disturbances on vertical velocity error and therefore height tracking.
The option is disabled by default.
These changes have been tested on replay and a single flight test.
**Vertical Velocity Consistency**
The following plots show the local vertical velocity (black), time …

EKF: add option to output velocity as time derivative of position

---

EKF/common.h
EKF/control.cpp
EKF/estimator_interface.h
EKF/mag_fusion.cpp

FYI @priseborough 
@CarlOlsson I have added a brief explanation of why this change is necessary:
Flight of fixed wing vehicles with a misaligned magnetometer or significant soft iron effects can result in the roll and pitch estimates being biased. This causes incorrect learning of X and Y delta velocity bias states.
If the vehicle is a type that changes to a different orientation for landing (eg tailsitter), then the incorrectly learned bias states will create errors in velocity and position tracking during landing.
The fusion mode added by PR prevents this occurring, but still enables the earth and mag bias field states to be learned during up ad away flight to be used during landing to constrain heading drift if required.

EKF: Add feature to use the mag to only update the mag states

---

EKF/common.h
EKF/estimator_interface.cpp

If the longest time delay sensor(eg GPS) has significant jitter in the arrival time of the updates, then this can cause the time stamp to fall outside of the buffer wind, resulting in the measurement being fused at the incorrect time. See below for an example of the effect a periodic 1-sample GPS timing jitter this can have on GPS position innovations with a GPs with an 85 msec delay parameter  and the buffer length set automatically at 96 msec. This output was generated from replay of data with a large GPS jitter.
In this  instance, manually setting the buffer length to 200 msec using the min_delay_ms parameter, and repeating the replay significantly reduced the position innovation spikes during forward flight.
The reason we do not set the buffers to a large value permanently is that …

EKF: Add a parameter to enable setting of a minimum buffer length

---

EKF/common.h
EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/vel_pos_fusion.cpp

@priseborough This is a first shot at implementing range finder aid when the primary height source is not range finder.
I moved all the control logic for height source selection into one function. Also I have a function which decides if conditions are met to switch to range finder. I still need to implement better checks, e.g. figure out if terrain height is stable, ...
I did some flight tests on Friday but did some changes after. So I'll get new logs and post them here.
This PR also included two bug fixes:
1) baro offset filtering was not working
2) resetting height based on range finder was not correct

Pr range aid

---

EKF/control.cpp

It hasn't done any harm so far because I don't know anyone who uses external vision for height estimation. But I cannot see why `_rng_hgt_faulty` is set to `true` at this point. There isn't even a check. Maybe I'm missing something?

remove setting rng faulty in ev mode because not checked

---

EKF/control.cpp

reset from baro to gps and from gps to baro did not exist in `ControlHeightFusion()` and gps was always faulty because `_gps_buffer` didn't have any measurements because they got remove with `pop_first_older_than()`

Pr height fixes

---

EKF/ekf.cpp

As discussed in https://github.com/PX4/ecl/issues/290, I changed it to use baro if range finder is primary height.

use baro for the ekf alignment if range finder is primary height source

---

EKF/airspeed_fusion.cpp
EKF/common.h
EKF/control.cpp
EKF/drag_fusion.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
EKF/mag_fusion.cpp
EKF/optflow_fusion.cpp
EKF/sideslip_fusion.cpp

The EKF common.h typedefs were conflicting with using the typedefs in Matrix. It became an issue when trying to use the typedefs in the WIP PX4 wind_estimator.

EKF matrix typedef cleanup

---

EKF/common.h
EKF/covariance.cpp

1) Variances for each axis  are increased to prevent the ratio of the largest to smallest value exceeding 100. Large ratios can result in poor stability of the delta velocity bias state covariance prediction and update operations.
2) The covariance prediction step explicitly constrains the variance from falling below the target minimum of 1E-8 which is equivalent to about 0.01 m/sec^2 of accel bias uncertainty. 
These changes improve the protection against badly conditioned IMU delta velocity bias state variances. This is necessary due to the limitations associated with single precision arithmetic that limits the range of values that can be used for the EKF2_ACC_B_NOISE parameter. The order and rate that different sensors are fused changes the minimum safe value for this parameter meaning …

EKF: Improve protection against covariance instability in delta velocity bias states

---

EKF/control.cpp

Without this fix, the system constantly re-initialises the vision position and state estimator when new vision data becomes available.

Fixed vision position fusion bug

---

EKF/control.cpp

This lowers the offset error when switching to range finder in range aid mode.

rng aid: use hysteresis with lower hagl check

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/gps_checks.cpp
EKF/vel_pos_fusion.cpp

Fuse external vision data using a relative position odometry method when GPS data is also being used and enable both GPOS and EV data to be fused on the same time step.
The previous filter logic turned of EV data fusion when GPS data was present to avoid conflict between the two data sources. This PR switches to using a delta position observation model for EV position data when GPs data is also being fused.
Initial response to https://github.com/PX4/Firmware/issues/7408
A replay log containing EV and GPs data is required to test this. This should be obtained with SDLOG_MODE = 2 and EKF2_REC_RPL = 1

EKF: Add ability to use EV and GPS data together

---

EKF/common.h
EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp

This PR improves the handling of in-flight yaw reset and magnetometer error handling   and further develops the functionality introduced by https://github.com/PX4/ecl/pull/294 which was able to recover from yaw errors present at launch/takeoff.
The following functions have been added:
If the EKF rejects GPS data long enough to result in an in-flight reset (which also causes loss of global position validity), then the yaw will be reset to the wind relative GPS course over ground vector.
If two in-flight mag yaw failure and reset events occur, then the mag is declared as unhealthy and magnetometer fusion is halted resulting in a warning message to the console:
"EKF stopping magnetometer use"
and bit position 18 in the filter status message being set to true.
**Testing**
Testing is ongoing …

EKF: Improve in-flight mag error detection, recovery and isolation for fixed wing

---

.travis.yml
EKF/CMakeLists.txt
EKF/estimator_interface.h
EKF/tests/pytest/ekf_test
EKF/tests/pytest/lint
EKF/tests/pytest/plot_utils.py
EKF/tests/pytest/requirements.txt
EKF/tests/pytest/test_altitude.py
EKF/tests/pytest/test_basics.py
EKF/tests/pytest/test_sampling.py
EKF/tests/pytest/test_utils.py
build.sh
swig/ecl.i
swig/numpy.i

In order to facilitate adding tests for ecl (unfortunately I am not that fond of writing unit tests in C++ :-)), I wrote a (very simple) Python wrapper based on SWIG. Exploiting Python libraries (pytest, hypothesis, and optionally matplotlib), one can now easily add assert-based tests, property-based tests, as well as plot data during (selected) tests.
To test my work, please checkout my branch and run `cmake -DPythonTests=1 ../EKF && make pytest-quick`. You can also run `make pytest-plots` to see graphs like the attached...
If you agree with this general approach, one could refactor the main classes in the C++ code slightly to make the wrapper more elegant and powerful.
Before I go any further though, please let me know what you think. I would love to hear your feedback. 
Peter

Python based testing

---

EKF/control.cpp
EKF/optflow_fusion.cpp

This fixes two bugs and one vulnerability:
1) The autopilot IMU data was not being accumulated across the  same timer interval as the flow data.
2) The autopilot IMU data used as a reference was not bias corrected
3) The delta time checks were too strict and could fail if high speed flow sensing was used.
Replaces https://github.com/PX4/ecl/pull/324

EKF: Fix bug in accumulation of IMU data for flow sensor gyro bias

---

EKF/control.cpp
EKF/estimator_interface.cpp
EKF/terrain_estimator.cpp

Fixes https://github.com/PX4/Firmware/issues/8102
The lines
```
optflow_sample_new.flowRadXYcomp(0) = optflow_sample_new.flowRadXY(0) - optflow_sample_new.gyroXYZ(0);
optflow_sample_new.flowRadXYcomp(1) = optflow_sample_new.flowRadXY(1) - optflow_sample_new.gyroXYZ(1);
```
result in,
```
optflow_sample_new.flowRadXYcomp(0) = + flow->gyrodata(0) - (- flow->gyrodata(0))
optflow_sample_new.flowRadXYcomp(1) = + flow->gyrodata(1) - (- flow->gyrodata(1))
```
if the vehicle is on ground and flow quality is not good, which is non-zero.

ekf: fix optical flow bugs

---

EKF/common.h
EKF/control.cpp
EKF/ekf_helper.cpp
EKF/mag_fusion.cpp

Adds a mode where if flying as a fixed wing vehicle, 3D mag fusion is only used to update the field estimates. This prevents misaligned mag or soft iron effects biasing the vehicle attitude solution and causing incorrect accel bias values that can cause undesirable velocity estimation error transients when transitioning back into RW flight if the transition involves a large attitude change.

EKF Add mag fusion mode for VTOL

---

EKF/covariance.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h

This will be required as part of the fixes to IMU sensor fallback logic raised here https://github.com/PX4/Firmware/issues/8186
Test results will be added when the supporting code on the other side of the interface has been completed.

EKF: Add method to enable the IMU bias states to be reset externally

---

EKF/estimator_interface.h

Sustained yaw spinning during hover can result in a gradual divergence of the Z accel bias estimate and increase in vertical position and velocity innovations. I some cases this can result in an estimation error that prevents the height controller completing a landing.
This is caused by the covariance prediction slightly lagging the vehicle motion due to the 12msec prediction time step (the output observer runs at the IMU rate of 4msec).
Here are the vertical innovations for replay of a log that demonstrates the behaviour 
Reducing the EKF internal prediction time step from 12 to 8 msec eliminated the problem.
**NOTE**
**Requires an increase in RAM allocation of 837 Bytes to allow for the longer IMU and output predictor buffers that can be created.**
**Processor utilisation on a pixracer …

EKF: Improve accuracy during sustained yaw spinning

---

EKF/RingBuffer.h
EKF/airspeed_fusion.cpp
EKF/common.h
EKF/control.cpp
EKF/covariance.cpp
EKF/ekf_helper.cpp
EKF/gps_checks.cpp
EKF/terrain_estimator.cpp

The default type for XeY is float

EKF: use int cast for XeY to avoid float casting of variables

---

EKF/common.h
EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
EKF/vel_pos_fusion.cpp

This PR adds a parameter activated function that uses the navigation to body frame quaternion from the external vision system to estimate the rotation from the EKF to the EV reference frame. This is then used to rotate EV position measurements into the EKF NED navigation frame before they are used.
It has been created in response to requirements identified in https://github.com/PX4/Firmware/issues/7408.
This function is enabled by setting bit position 6 in EKF2_AID_MASK to true. If bit position 4 is also set to true (EKF is using the EV system's yaw angle) then the compensation is disabled because the EV system's navigation frame becomes the reference.
**TESTING**
Testing has been performed using SITL with the following branch to enable the EV data to be rotated into a different frame of …

EKF: Enable operation with arbitrary External Vision reference frame

---

EKF/RingBuffer.h
EKF/estimator_interface.cpp
EKF/estimator_interface.h

This PR reduces the amount of memory required by the observation data buffers by initialising each buffer to an initial length of 1. The buffer is not set to it's required length until the first data arrives. This saves over 1kB of memory because typically only half of the available observation types are used.
To prevent repeated allocation failures causing problems, each buffer is given one attempt to allocate the required memory. If memory cannot be allocated, a fault condition is reported and the corresponding observation will not be used.
Hardware testing TBD.

EKF: Reduce memory usage

---

EKF/RingBuffer.h
EKF/estimator_interface.cpp
EKF/estimator_interface.h

Expanding the simple status for command line debugging. This is crude, but helps give you an idea where the memory is going.
nsh> ekf2 status
INFO  [ekf2] time slip: -40 us
INFO  [ekf2] Ekf2 class: 6896 Bytes
INFO  [ekf2] Ekf2 stack size: 6600 Bytes
INFO  [lib__ecl] local position valid: no
INFO  [lib__ecl] global position valid: no
INFO  [lib__ecl] imu buffer: 22 (888 Bytes)
INFO  [lib__ecl] gps buffer: 14 (680 Bytes)
INFO  [lib__ecl] mag buffer: 14 (344 Bytes)
INFO  [lib__ecl] baro buffer: 14 (232 Bytes)
INFO  [lib__ecl] range buffer: 1 (24 Bytes)
INFO  [lib__ecl] airspeed buffer: 1 (24 Bytes)
INFO  [lib__ecl] flow buffer: 1 (56 Bytes)
INFO  [lib__ecl] ext vision buffer: 1 (56 Bytes)
INFO  [lib__ecl] output buffer: 22 (1064 Bytes)
INFO  [lib__ecl] output vert buffer: 22 (536 Bytes)
INFO …

EKF RingBuffer allocation minor improvements + print memory usage

---

EKF/common.h
EKF/control.cpp
EKF/estimator_interface.h
EKF/vel_pos_fusion.cpp

Addresses #217 
Can be used to reduced the effect of ground effect induced static pressure rise during takeoff and landing. When rotary wing vehicles take off, the rotor wash often induces an increase in static pressure which causes the baro height to read low with a transient that is typically up to 5m for commonly used disc loadings and fuselage and rotor relative positions heights. The symptons observed by the pilot are typically an overshoot of the initial height demand, followed by a slow descent as the estimator recovers.
- This PR adds a method which applies a dead-band to the vertical position innovation if using baro for height and if in the ground effect region during and just after takeoff.
- The method needs to be activated externally.
- The method turns off automatically …

EKF: Protect against ground effect induced static pressure rise

---

EKF/control.cpp
EKF/vel_pos_fusion.cpp

Fixes a bug introduced by commit 882f4d4 that incorrectly handles vertical velocity and position innovations.
Before - vertical innovations are not output by the EKF:
After - now they are:

EKF: Fix vel pos innovation handling bug

---

EKF/ekf.h
EKF/ekf_helper.cpp

When GPS use is gained whilst flying using optical flow data, the release of the speed limit can cause unexpected change in responsiveness the first time the operator moves the vehicle after the limit is released.
When another source of external aiding (eg GPS) is gained, this patch releases the speed limit as height is gained, but does not reduce it when the vehicle descends,  unless other aiding is lost and optical flow becomes the only source of aiding again.
Flight tested on a px4fmu-v4 board using https://github.com/PX4/Firmware/pull/8223
Test Log: https://logs.px4.io/plot_app?log=4bdc4540-9a52-450a-a14e-afeac2606f3d

EKF: Release flow speed limit progressively

---

EKF/ekf.h

Gate size class variables should not be initialised to zero, because it will cause a /0 error if fuseVelPosHeight() is called before they are set to their respective parameter values.
With current order of processing this is not a problem, but future changes could expose this condition.

EKF: Prevent possible /0 due to incorrect initial values

---

EKF/control.cpp
EKF/ekf_helper.cpp

Currently, the EV fallback to baro does not work -> https://review.px4.io/plot_app?log=e095c33e-e72d-48a1-aa5e-8386581fe46a
I also had to add the reset `vert_pos_reset` of EV data is available again. Otherwise the Z setpoint would stay at baro altitudes.
Here's a log of this PR with EV aiding, then losing EV data and regaining it. https://review.px4.io/plot_app?log=f2d565a4-d0a6-4806-9345-27a84a549d90
Tested with https://github.com/PX4/Firmware/pull/8642#issuecomment-357547759

EV height reset

---

EKF/ekf.h
EKF/ekf_helper.cpp
validation/data_validator.cpp
validation/data_validator.h
validation/data_validator_group.cpp
validation/data_validator_group.h

This reverts commit e70206f74bc4f77a0e000da3c923f4459006d2b1.
The reason for this is that the release in the optical flow speed limit only with altitude after commencing GPS fusion was not liked by testers and has been replaced with a better method implemented inside the position controller.
See https://github.com/PX4/Firmware/pull/8223 for details

Revert "EKF: Release flow speed limit with altitude gained"

---

tecs/tecs.cpp

Fixes https://github.com/PX4/ecl/issues/384
The if() statement was there as provision to do something different with the speed demand derivative limits if an abnormal condition was present, however we have no basis for assigning different limits at this point in time.

tecs: Remove redundant code

---

validation/data_validator.cpp
validation/data_validator.h
validation/data_validator_group.cpp
validation/data_validator_group.h

This brings back https://github.com/PX4/ecl/pull/377, which got reverted in https://github.com/PX4/ecl/pull/382, because of a CI failure (a variable shadowing problem).

Reverse the linked list of data_validator_group #2

---

EKF/ekf_helper.cpp

Required to prevent large transients in value returned by get_pos_d_deriv accessor following a vertical state reset event.
Fixes https://github.com/PX4/ecl/issues/390.
Bench tested by adding a time based baro offset of +100m at 50 seconds in ekf2_main.cpp. vertical derivative estimate now resets to same value as velocity following a reset.
m

EKF: Add missing reset for output observer vertical position derivative

---

EKF/ekf_helper.cpp

This fixes the external vision rotation matrix calculation. There were two issues:
* The spike handling added a fraction of `rot_vec` instead of `_input_delta_vec` to `_ev_rot_vec_filt`
* The vector from quaternion calculation must have had a bug somewhere. I just swapped to using the matrix library which also reduces duplicate code.
This has been tested in sitl using `make posix_sitl_default gazebo_iris_opt_flow` with `EKF2_AID_MASK` set to `72`.

ekf fix ev rotation calculation

---

EKF/control.cpp

This fixes a bug introduced by an earlier feature request PR. The noise parameter is supposed to define the lower limit on the observation noise.
Bug spotted by Deon Blaauw https://px4.slack.com/archives/C643UJTB7/p1519744752000030

EKF: Fix bug in use of gps velocity noise parameter

---

attitude_fw/ecl_controller.cpp
attitude_fw/ecl_controller.h
attitude_fw/ecl_pitch_controller.cpp
attitude_fw/ecl_pitch_controller.h
attitude_fw/ecl_roll_controller.cpp
attitude_fw/ecl_yaw_controller.cpp

Angular rate limits should be applied to body angular rate references, as opposed to the non-transformed Euler rate references.
(follow-up from #402)

attitude_fw: move angular rate limits to body angular rates

---

tecs/tecs.cpp

When initialised in air the throttle integrator was set to cruise throttle which does not make any sense.
The cruise throttle value is separately added to the throttle value and does not need to be part of the integrator.
However, for the last throttle value variable (used for slew rate limiting) it makes sense to initialise it with cruise throttle when TECS is initialised in air.

tecs.cpp: tecs initialisation fixes

---

CMakeLists.txt
airdata/WindEstimator.cpp
airdata/WindEstimator.hpp
airdata/python/wind_est_derivation.py

I would like to add the wind & airspeed scale estimator to the ecl library since I think it's the best place for it to live.
Just like the ekf it has a clear interface and could easily be deployed on other platforms.
On the Firmware side we still need to discuss if we want to integrate this into the ekf2 module or if we implement a standalone work queue which uses this library.
TODO:

added airdata module which contains wind & airspeed scale estimator

---

EKF/control.cpp
EKF/ekf_helper.cpp

This fixes the following:
1) If reversion to no-aiding from use of GPS was demanded by setting the EKF2_AID_MASK parameter, the reversion still waited for the full timeout period to pass which allowed state estimation errors to accumulate.
2) After reversion, there was a race condition that could cause the last GPS vertical velocity innovation to be repeatedly fused which biased the vertical velocity and position states.
3) Reset of the position and velocity states was not using the helper functions

EKF: Fix reversion from GPS to no-aiding mode

---

EKF/control.cpp

If we are using other sources of aiding (eg optical flow or external vision), then we should relax the upper GPS position observation noise limit which reduces the effect of large GPS position jumps.
If we are not using another source of aiding, then we are reliant on the GPS observations to constrain attitude errors and should prevent the observation noise value becoming too large.

EKF: Reduce effect of GPS noise when using other aiding sources

---

EKF/common.h
EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/terrain_estimator.cpp

This fixes the following problems with use of optical flow and external vision data.
Both the optical flow and external vision data fusion logic were missing functionality required to ensure that the EKF would reset to the observation if innovation checks failed for too long and the data was the only source of aiding.
The velocity reset method did not handle optical flow measurements and instead initialised velocity to zero if optical flow data was the aiding source.
The velocity reset function did not separate the optical flow and external vision use cases properly.
The position reset function selected optical flow data before external vision data, even though optical flow data does not provide position information.
The timeouts used to declare stoppage of optical flow and external …

EKF: Fix non GPS aiding data reset logic

---

EKF/vel_pos_fusion.cpp

This bug causes the last vertical velocity observation to be continuously fused after GPS use stops unless the EKF reverts non aiding mode. The symptons are persistent height innovation offsets if GPS use stops and navigation continues with use of optical flow or external vision observations. The following plot shows the behaviour before the fix for a flight where navigation continues using optical flow after GPS becomes obscured. Note the significant change in baro height innovation.
The same test performed after the fix:

EKF: fix bug causing height offset when GPS use stops

---

EKF/common.h
EKF/estimator_interface.cpp

@DanielePettenuzzo I tried to change the logic so that we can remove multiple checks for no_gyro flag.
Basically I think if we figure out that we have no gyro data from the flow sensor we can get a gyro sample from the buffer, convert it into a gyro rate, and then back to a delta angle using the dt from the flow sensor.
I hope I did not oversee something here.
@priseborough FYI, I corrected the units in the comment for the flow message (common.h)

Pr no gyro opt flow

---

EKF/control.cpp

This pr fixes negative vision timeout. This can happen if last vision timestamp is greater then last imu timestamp and it would trigger false ev timeout.

fix negative vision timeout

---

EKF/control.cpp

Minimum change fix to address https://github.com/PX4/Firmware/issues/9527
Replaces https://github.com/PX4/ecl/pull/461
This fixes a error condition that occurs if _time_last_gps is greater than _time_last_imu.
By checking time stamps at the fusion time horizon, we guarantee that this cannot happen because all observations must have a time stamp smaller or equal to _imu_sample_delayed.time_us before they are retrieved from the buffers.
There are other instances in code where this type of error could occur for other observation types. These will be addressed as part of a separate PR following a more thorough code review.

EKF: Fix timestamp comparison issue

---

EKF/common.h
EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/optflow_fusion.cpp

Replaces https://github.com/PX4/ecl/pull/453
If optical flow gyro delta angles are set to NAN, then the EKF's internal IMU sample will be used.
TODO testing

EKF: Enable use of flow sensors that do not have gyros

---

EKF/control.cpp

The result of multiple changes to the ekf2 module and ecl library is that we do not discard range finder data that is outside the min and max limits written to the ekf  here https://github.com/PX4/Firmware/blob/master/src/modules/ekf2/ekf2_main.cpp#L957

EKF: Add missing range validity check

---

EKF/control.cpp
EKF/ekf.cpp

This allows initialization of the attitude estimate without receiving vision messages first. It also automatically resets the calculated rotation matrix from navigation frame to vision frame in the event of a vision (re)-init, since the visual estimator will have a new origin whenever it resets.
This is a first in a series of PRs which will be robustifying vision-GPS-OF flight over the next few weeks.

EKF : allow init without external vision measurements

---

EKF/common.h
EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h

**DESCRIPTION**
This brings all the range finder data checks (excluding innovation consistency checks) into one place and eliminates the need to perform range checking external to the library. Having checks in multiple places has previously resulted in unintended loss of functionality over time which had to be fixed by https://github.com/PX4/ecl/pull/476. This PR should reduce the likelihood of this type of bug being introduced in the future.
The hard coded optical flow tilt limit has also been  changed to use the same value as the range finder for consistency.
Variable names have been changed changed to make a clear distinction between the max/min values calculated by by the stuck range check and the max/min valid values published by the sensor.
**TESTING**
For full test coverage we …

EKF: Consolidate range finder checking

---

EKF/common.h
EKF/control.cpp
EKF/ekf.h

1.Disable optical flow fuse when the flow quality is poor, it will also use poor flow data in altitude mode which will cause velocity to diverge and out of control.
this issue will occurs with EKF2_OF_QMIN value of 1 and poor flow quality, tesing with EKF2_OF_QMIN value of 100 and 40, I found that the optical flow data was used in altitude mode when it is poor quality.
issue log link: https://logs.px4.io/plot_app?log=3d21e384-6bf1-4009-a605-a8d8a3063af2 (EKF2_OF_QMIN = 100)
https://logs.px4.io/plot_app?log=13445020-c395-480d-aaf7-de21d58d33fd (EKF2_OF_QMIN = 40)
https://logs.px4.io/plot_app?log=4546e851-5584-4449-8138-79174aebe51b (EKF2_OF_QMIN = 1)
log with fixs: https://logs.px4.io/plot_app?log=3b1def27-95e5-489f-bc07-36a18df14ac4
2. Add a variable to enable or disable the check of …

Ekf opt flow fixes poor flow quality

---

EKF/control.cpp

Removed `if` statement that would prevent the update of the `_rng_hgt_faulty` flag.

Remove if statement in checkRangeDataValidity

---

EKF/estimator_interface.cpp
EKF/optflow_fusion.cpp

Fixes for optical flow:
1) Fixed calculation of flow sensor velocity relative to IMU
2) When computing the height above ground for flow calculations take into account that the flow camera can be offset from the IMU.
3) Fixed comment.

Pr opt flow

---

EKF/gps_checks.cpp

Enables default enabling of the position drift and velocity checks during preflight. These can tell if the GPS position is unstable and do not rely on the GPS receivers own reported accuracy which can be optimistic in some signal environments.
Required to fix https://github.com/PX4/Firmware/issues/9549.
Requires https://github.com/PX4/Firmware/pull/9999 to adjust parameters.
**TESTING**
Preliminary test log: https://logs.px4.io/plot_app?log=6cd9fb22-6339-4c79-a100-32435d54505e
The drift check failure flags did not activate (other than momentarily)  when the vehicle was picked up and carried whilst outdoors, but did fail after it was carried indoors.

EKF: Disable GPS drift checks when the vehicle is being carried

---

EKF/estimator_interface.h

Refer to https://github.com/PX4/Firmware/issues/10023
The function name and documentation are misleading given the function is only a getter.
This change makes the usage clearer.
The function is not currently used by PX4/Firmware.

EKF: Correct documentation and function name for declination accessor

---

l1/ecl_l1_pos_controller.cpp
l1/ecl_l1_pos_controller.h

This adds slew rate limiting of the roll angle setpoint to the l1 controller.
It also implements a private method to calculate the roll setpoint (update_roll_setpoint) and a public method to get the roll setpoint (get_roll_setpoint). Previously the roll setpoint was calculated more than one time during one control cycle.
The aim of this is to avoid sudden steps in roll angle setpoint which can occur if there is a switch in waypoints.

l1 position control: added roll angle setpoint slew rate limiting

---

l1/ecl_l1_pos_controller.cpp

@eyeam3 mentioned that under certain circumstances the the l1 position controller can produce a NAN roll setpoint. If we don't protect the slew rate limit logic against this the state will not be able to recover.
@eyeam3 Thanks for your input! Do you want to review? :-)

l1 position controller: protect against NAN

---

EKF/ekf_helper.cpp

This PR adds a check for **range aiding** to determine if we are `relying_on_rangefinder`. This fixes the bug we are experiencing where we are limited to the range finders max height above ground when using it in aiding mode. If range aiding is not enabled, and thus the range finder _is_ intended to be the sole source of height observation, then this check will evaluate true and the controller will still properly limit the height above ground.
Let me know if you have any questions or concerns, thanks!
Jake

Fix invisible ceiling when using range aiding

---

EKF/estimator_interface.cpp

Fixes potential fault condition whereby if optical flow sensor started out of focus with quality below startup minimum, then optical flow fusion would never start.
May be relevant to issue reported here: https://github.com/PX4/ecl/pull/498#issuecomment-417810912
Log of successful  SITL test here: https://logs.px4.io/plot_app?log=03ecea26-9024-4f7f-8377-977cb63fdc32
Flow Innovations:
Flow Quality - note it starts at zero when simulated sensor is close to ground

EKF:  enable optical flow use to bootstrap when quality poor

---

EKF/control.cpp
EKF/terrain_estimator.cpp

The EKF would not correctly detect when it stopped fusing optical flow due to failing checks (e.g motion  excessive, or invalid terrain estimate), and eventually diverge without any aiding source. 
Commits : 
1. Fixes a corner case in the terrain estimator, where range data newer than the IMU sample would cause an overflow due to unsigned math, similar to https://github.com/PX4/ecl/pull/462. This is still a problem in some other places in ECL, and I will be fixing them incrementally.
2. Fixes the flow  aiding timeout check to use the last time optical flow was fused instead of the time the last sample is from.
Testing  :  
https://logs.px4.io/plot_app?log=ea18fc88-8ce5-4382-ab62-35a9a0d015f3
The log was replayed without this fix, and then with this fix. The estimator does not diverge in …

EKF : Fix divergence when optical flow is not fused for a long time

---

EKF/common.h
EKF/estimator_interface.cpp
EKF/vel_pos_fusion.cpp

For the vision input to the ekf there is only single variance figure used (`posErr` in the structs) for position representing a spherical error around said position. Some companion computer sensor systems have different errors on horizontal and vertical positions. I guess this is one of the reasons you can set the height mode independently via the `EKF2_HGT_MODE` flag. 
I came across the issue where I wanted to influence the horizontal position accurately, but influence the vertical position only a little (or varying variances). 
I've expanded the struct in this repo and included a separate `hgtErr` which is used on this line instead. I've also modified `Firmware` to extract it from the mavlink message and pass it through. It's all tested and working with the variance correctly …

Add vision height covariance passthrough

---

EKF/estimator_interface.cpp

The handling of invalid flow data when on ground is performed in controlOpticalFlowFusion() where it is able to handle the case of flow sensors that don't publish gyro data. By handling the on-ground with invalid flow data case in the interface before data is pushed into the buffer, the change introduced by commit a53ad9c removed the ability to handle flow sensors that publish NAN for gyro data. This was not picked up in testing because the SITL model does nor simulate that type of sensor.
**Testing**
Testing performed was on SITL with 'make posix gazebo_iris_opt_flow' target
Default test log with flow sensor gyro data: https://logs.px4.io/plot_app?log=ca849660-3d78-4a60-833e-84d1ad9dd63e
The simulator_mavlink.cpp file was then modified to set the published flow gyro integral data to NAN …

EKF: Fix bug that prevents use of flow sensors without gyros

---

EKF/control.cpp

When using 3D mag fusion only I noticed that the magnetic declination was not calculated from the actual magnetic field states. So basically the code would never step into this if statement:
https://github.com/PX4/ecl/blob/master/EKF/ekf_helper.cpp#L756
I realized that this was because the _flt_mag_align_complete flag was never set when using 3D mag fusion only.

3D only mag fusion: use declination calculated from magnetic field states

---

EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/gps_checks.cpp

Fixes issue reported here: https://github.com/PX4/ecl/issues/519
**TESTING**
Testing performed in SITL with gazebo_gps_plugin.h modified to use following WGS-84 position
// Seattle downtown (15 deg declination): 47.592182, -122.316031
double lat_home = 47.592182 * M_PI / 180;    // rad
double lon_home = -122.316031 * M_PI / 180;  // rad
double alt_home = 86.0;                      // meters
and SDLOG_MODE = 1 to start logging from boot.
Before Changes Log: https://logs.px4.io/plot_app?log=479aba4f-d2f1-4fb3-b31d-8da8b4422f36
After Changes Log: https://logs.px4.io/plot_app?log=24a35542-4512-4342-b8cb-a49c3f6a3607
Because this does enforce reset the quaternion states for small angle changes less than 15 degrees that were previously ignored, flight testing is required to ensure that the …

EKF: Ensure yaw gets reset when declination is set

---

EKF/terrain_estimator.cpp

_params.vehicle_variance_scaler was never used

terrain_estimator: add vehicle_variance_scaler

---

EKF/ekf_helper.cpp

Fixes the issue reported by https://github.com/PX4/Firmware/issues/9716
TODO Further testing with starting and stopping GPS use when EKF2_MAG_TYPE = 4

EKF: Fix EKF initialisation bug

---

EKF/ekf_helper.cpp

in initialiseFilter() we low pass filter the measurements from the magnetometer, however when initializing the heading we took the last value from the mag instead of the filtered values. At least in SITL this sometimes results in up to 5 degrees heading error at bootup

EKF: use low pass filtered mag measurements for heading initialization

---

EKF/control.cpp

Due to a combination of previous changes, the reset of the yaw when climbing above 1.5m was not performed until 3-axis fusion was enabled. This could result in loss of navigation if the ground level magnetic declination error was large enough and the value of  EKF2_MAG_TYPE and the flight profile did not cause the EKF to commence 3-axis fusion.
SITL test log before fix: https://logs.px4.io/plot_app?log=c9f62df4-3898-4e61-b6e0-791d984ea964
SITL test log after fix: https://logs.px4.io/plot_app?log=66c9b4a1-1d67-4b66-a424-fc7e5b165075
These were tested using the following modification to sitl_gazebo: https://github.com/priseborough/sitl_gazebo/commit/16a86ee1352e4cbf6c1f18f9047a1bc8d0613f7c
We need a way to incorporate this type of magnetic field error into the reversion testing.

EKF: Critical yaw reset bug fix

---

EKF/ekf_helper.cpp

Fixes https://github.com/PX4/ecl/issues/548
When using magnetometer as the primary yaw reference for a yaw angle reset, the mag heading uncertainty should always be used to set the variance of the rotation vector Z-axis.  The external vision angular uncertainty should only be used when external vision data is being used as the yaw reference.

EKF: Fix bug causing incorrect yaw variance value to be used after a reset

---

EKF/optflow_fusion.cpp
geo/geo.cpp
validation/data_validator_group.cpp

- <cfloat> isn't available in the NuttX c++ library
https://github.com/PX4/Firmware/issues/11152

replace <cfloat> with <float.h>

---

EKF/common.h
EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp

@priseborough I added the flt_mag_align_complete to the control_status flags since it controls quite some things internally in the EKF

EKF: add flt_mag_align_complete to control_status flags

---

EKF/control.cpp
EKF/estimator_interface.cpp

EKF waits 10s after GPS signal is lost before setting GPS control status flag to false. As the position information given by the alternative position sources drifts from the last GPS position, the controller over corrects.
With this update, the time horizon until GPS control flag set to false is reduced to 1s , if an alternative position source is available such as optical flow or external vision.
Tested with optical flow as position source
-  log from as is https://review.px4.io/plot_app?log=d624af5e-dde4-40ab-ba5b-a693a49f5a36 
-  log with update https://review.px4.io/plot_app?log=13ed6dc3-22dd-43f8-b898-4add41d60439
Also increase optical flow buffer length.
@priseborough

add GPS dropout case

---

EKF/estimator_interface.h
ecl.h

This adds support for the paparazzi autopilot to use this library as EKF.
The header order change has to be done in order to have `std.h` included to get certain defines at the start of the `estimator_interface.h`.

Add Paparazzi compatibility

---

CMakeLists.txt
EKF/ekf.h
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/gps_checks.cpp
EKF/tests/base/base.cpp
EKF/tests/ringbuffer/ringbuffer.cpp
attitude_fw/ecl_controller.cpp
attitude_fw/ecl_controller.h
attitude_fw/ecl_pitch_controller.cpp
attitude_fw/ecl_pitch_controller.h
attitude_fw/ecl_roll_controller.cpp
attitude_fw/ecl_roll_controller.h
attitude_fw/ecl_wheel_controller.cpp
attitude_fw/ecl_wheel_controller.h
attitude_fw/ecl_yaw_controller.cpp
attitude_fw/ecl_yaw_controller.h

- fixes https://github.com/PX4/ecl/issues/581
- PX4/Firmware side https://github.com/PX4/Firmware/pull/11594
@fvantienen

EKF drop unused timestamp from collect_gps() and pass data by const reference

---

EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h

This PR aims to improve the interface with the covariances obtained by EKF. It extends far beyond the the existent method `get_covariances()`, by also adding ways of obtaining dimensions covariances.
Allows:
- obtain the full state covariances matrix;
- obtain the position, the quaternion and the velocity covariance;
- by implementing the covariances law, one is now able to obtain the 3x3 covariance from the euler anges, which is useful for the current odometry pipeline implemented on PX4;
- merges the position and orientation (euler) covariances into a single pose covariance, which not being a cross-covariance matrix, it helps at least to parse it to the PX4 internals.

ekf_helper: add more useful methods to interface with the covariances

---

validation/CMakeLists.txt
validation/tests/CMakeLists.txt
validation/tests/test_data_validator.cpp

Added a few unit tests for the `DataValidator` class that cover happy path and common failure paths. In some cases the existing interface lacks documentation of expected behavior (for example `DataValidator::confidence` has some undocumented side-effects, setting `_error_mask`, and `put` performs a variety of calculations), so these tests codify some of the "as-built" behavior of the class.  I did not yet attempt to test the vibration-calculating code, which is unspecified but appears to be key to the operation of `DataValidatorGroup`.

Add unit tests for DataValidator

---

EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp

This PR fixes several issues that were present in the initialization of the attitude covariances and the output filter buffer.
- Issue 1: The attitude covariances were initialized [before the attitude](https://github.com/PX4/ecl/blob/a85d3a43edc4ac4b85ae21159510b9c26f7359e6/EKF/ekf.cpp#L235-L253) which does not work properly since the initialization is [dependent on the attitude](https://github.com/PX4/ecl/blob/a85d3a43edc4ac4b85ae21159510b9c26f7359e6/EKF/ekf_helper.cpp#L1462-L1478).
- Issue 2: After the attitude was initialized we [rotate the yaw angle](https://github.com/PX4/ecl/blob/a85d3a43edc4ac4b85ae21159510b9c26f7359e6/EKF/ekf.cpp#L265-L265). In this function we also rotated all attitude solutions in the output buffer. However, the data in the buffer did not include the tilt …

EKF: fix covariance and output filter buffer initialization

---

EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
EKF/mag_fusion.cpp

Before we only calculated the `_mag_declination` variable before mag fusion, leading to the fact that in fuseDeclination() the innovation was not zero (since mag fusion updated the states) even though mag_align_complete was true.

EKF: Fix innovation in fuseDeclination()

---

EKF/common.h
EKF/covariance.cpp
EKF/ekf.h

This PR scales the wind process noise with low pass filtered height rate in order to faster learn the wind states at high altitude gradients

EKF: scale wind process noise with low pass filtered height rate

---

EKF/control.cpp

Ground effect compensation activation logic for systems without a range finder has been implemented in
https://github.com/PX4/Firmware/pull/11592
However, the ekf would deactivate ground effect compensation when the vehicle was in_air and not close to the takeoff altitude. This means that ground effect compensation did not work if the user took off from some altitude and tried to land the drone at a higher altitude.

ground effect: removed dependency on local position

---

EKF/control.cpp

Fixes https://github.com/PX4/ecl/issues/575
SITL test log here: https://logs.px4.io/plot_app?log=2e403ed3-2189-443b-b72d-504a9541ac1d with EKF2_MAG_TYPE = 2
Print statements at each call to resetMagHeading() were use to verify that reset only occurred at the following events:
1. State vector initialisation (does not increment quaternion reset count)
2. Completion of tilt alignment
3. Commencement of GPS aiding when local declination was available
4. When 1.5 metres was cleared after takeoff
Reset Counter:
Earth Field States:
XYZ Innovations:
Height:

EKF: Fix bug causing continual yaw reset when EKF2_MAG_TYPE = 2

---

EKF/control.cpp

Crucial fix for external vision.
When external data is stopped, EKF kept on fusing old data, resulting in a stuck heading.

EKF: control: stop vision yaw fusion on timeout

---

README.md

Once user guide became versioned, this was broken.

Fix up link to EKF docs

---

EKF/control.cpp
EKF/ekf.h
EKF/python/terrain_flow_derivation/derive_terrain_flow.py
EKF/terrain_estimator.cpp

This PR allows optical flow measurements to be used for terrain estimation. I see the following two cases when this could be useful:
- terrain estimation for fixed wing flight and auto land (potentially using the flow sensor at higher altitude and a lidar when close to the ground)
@priseborough already did this in another project and I believe he had good success with the [pmw3901](https://www.seeedstudio.com/Flow-Breakout-Board-p-2949.html) optical flow sensor.
- enhancement of the detection logic for ground effect (see https://github.com/PX4/Firmware/pull/11592 )
Flow measurements will only be fused in the terrain estimator if no range data is being fused and if the primary EKF is not fusing flow.
So far this has only been tested in SITL using iris_opt_flow model. Two logs are being …

Implemented use of optical flow for terrain estimation

---

EKF/ekf.h
EKF/gps_checks.cpp

Currently every time SITL starts up, the user has to wait for 10 seconds until GPS is reported as healthy. This is unnecessary and slows down development cycles, so this PR adds an interface to configure the required GPS time.
This does not change the default of 10 seconds.

add set_min_required_gps_health_time() to allow configure minimum GPS health time

---

geo_lookup/geo_mag_declination.cpp
mathlib/mathlib.cpp
mathlib/mathlib.h

When calculating the min_lat it was incorrectly casting to int which for negativ values will round up rather than round down. This will then result in a lat_scale/lon_scale that is forced to zero as lat/lon is a smaller value than min_lat/min_lon.

fixed calculation of magentic table values by using floor instead of int casting

---

geo_lookup/geo_mag_declination.cpp
mathlib/mathlib.cpp
mathlib/mathlib.h

In the current structure ecl uses an in tree mathlib.h when built standalone, otherwise it uses mathlib.h from PX4 when included in a submodule. Arguably this should be fixed, but at the moment it means ecl mathlib.h changes need to be mirrored in PX4.
All that is to say, let's not add anything to mathlib.h that we don't absolutely need.
https://github.com/PX4/ecl/pull/606#issuecomment-495651720

mathlib delete floorf in favor of math.h

---

EKF/CMakeLists.txt
EKF/covariance.cpp
EKF/ekf.h
EKF/ekf_helper.cpp

Each time there is a covariance matrix update we add process noise to the variance of each state.
For the delta angle and the delta velocity bias variances these contributions can be so small compared to the actual variance that they get lost due to numerical limitations when dealing with floating point variables.
One solution for this problem is to use the Kahan summation algorithm which relies on an accumulator variable which captures the small increments that would get lost otherwise.
For more details, see https://en.wikipedia.org/wiki/Kahan_summation_algorithm
Thanks to @priseborough for helping debug this issue and thanks to @jkflying for suggesting the algorithm.
Delta velocity z bias variance prior to this change:
Delta velocity z bias variance after this change:
I also compared …

Implemented Kahan summation algorithm for adding process noise

---

EKF/control.cpp
EKF/ekf.h
EKF/gps_checks.cpp

If GPS is being used as the primary height source (EKF2_HGT_MODE = 1) then the first 3D fix from the GPS is used to set the height origin. This can cause problems because these erarly estimates are inaccurate and can result in the EKF origin being out by 30m or more. The GPS height solution then improves and the large rapid change in measurement causes it to be rejected by the EKF until the height rejection timeout, resulting in a reset. The following figure shows the large innovations and the reset caused by this behaviour.
With this fix applied, replay of the same data shows the problem to be fixed.
This fix requires that the same GPS quality check used to determine if GPs can be used for navigation are also required before it can be used as the primary height sensor. The …

EKF: Fix bug allowing state initialisation to a bad GPS height

---

EKF/estimator_interface.h

The original issue is that `ekf2 status` reports `local position: valid` if it didn't receive any IMU data because the check is `!_deadreckon_time_exceeded`.

EKF - Initialize _deadrekon_time_exceeded to true.

---

geo/geo.cpp

When trying to initialize `globallocalconverter` using `globallocalconverter_init`, the return value of `map_projection_global_init` will always be 0 (As shown below), which will make the initialization of the globallocalconverter always fail.
https://github.com/Jaeyoung-Lim/ecl/blob/ab495c92fa49883d8adb7ffd1827133fcb4201b2/geo/geo.cpp#L90-L102
Changing the checks result in a successful initialization of the `globallocalconverter` and was used in a offboard local position setpoint implementation for fixed wing position control.

Fix flag globallocalconverter_init

---

CMakeLists.txt
EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h

These changes fix the alignment between the local origin frame and an external fixed frame of the external vision system. The changes contain:
- fix the computation of the orientation error between the frames
- enable access to the estimated alignment rotation
- removed mag suffix
- enable the computation of the orientation error only based on MASK_ROTATE_EV
- fixes wrong labeling of get_ekf2ev_quaternion function (also see: PR #635)
@priseborough

Fix alignment of external local frame 

---

EKF/control.cpp

I'm currently working on a drone with an optical flow sensor and is has a nasty attitude glitch at each stop. After analyzing the log, I found out that the vxy and xy reset counters are incremented every time the drone stops. The reset occurs at each stop because it goes in and out of flow aiding and that the condition for a reset is always true "if the vehicle doesn't have GPS or external vision aiding" (my vehicle has GPS but no EV); the correct check should be "if it doesn't have gps and doesn't have external vision aiding" or -as I implemented it here- "if flow is the only velocity/position aiding source".
Below a log showing that the reset counter is incremented every time the height source switches from baro (during motion) to range aid (after a stop).
@jkflying This should also fix …

Flow aiding - Reset state when flow is enabled only if it is the only position/velocity aiding sensor

---

EKF/common.h
EKF/control.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/terrain_estimator.cpp

This PR improves the behavior when taking off using only optical flow. Specifically:
- It publishes a "fake range measurement" when the vehicle is on the ground and range sensor data contains garbage. This change now publishes the value of the parameter `rng_gnd_clearance` in that case.
- It adds the range sensor quality to the terrain estimator. Fundamentally, the information is fused into the existing `_rng_hgt_faulty` flag. It is also used in the decision-making of the above point, as well as in the initialization of the height above ground `initHagl()`.
I've tested this on two different vehicles on PX4 with different range sensors:
- Using the CM8JL65, a lidar sensor which is quite accurate from 0.1m ~ 6m
- Using the MB12xx, a sonar which starts working around 0.65m ~ 5m
The drivers …

Flow takeoff improvements

---

EKF/control.cpp

Fixes https://github.com/PX4/Firmware/issues/12558
**Test flight log:**
* https://drive.google.com/open?id=1cEp38Vox5k4jaj3aGYZoe-yc6DTqrJjJ
* https://logs.px4.io/plot_app?log=1147e548-37b2-4b1f-b43f-37df05a0b5fa
**Screenshot:**
"Stopping GPS usage" happens at 141 seconds. EKF states reset to EV position. Local position is valid at all times, `pos_test_ratio` is ok (<1).

EKF: reset position when stopping GPS use and EV is active

---

EKF/control.cpp

Review needed, initial suggestion for fixing https://github.com/PX4/ecl/issues/625
This changes removes the mag innovation spikes from the plot in the issue and it can look like this now:
We see the heading drift in this plot though, so if we can get rid of that too it would be in an initial good working state.

EKF: Stop mag fusion when GPS heading fusion is active

---

EKF/terrain_estimator.cpp

Tiny detail we forgot in #639 :
If we are stationary on the ground, we want to fake a measurement both if:
- The range sensor doesn't report anything
- The range sensor reports garbage
The previous PR only handled the first case

EKF: fake rng if faulty on ground

---

CMakeLists.txt
EKF/ekf.h
EKF/estimator_interface.h
EKF/swig/ecl_EKF.i
airdata/WindEstimator.cpp
validation/tests/test_data_validator.cpp
validation/tests/test_data_validator_group.cpp

This removes direct access to the underlying datastructures in Matrix, replacing them with safe API calls.
@dagar

Remove direct unsafe access to matrix internal data

---

EKF/common.h
EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/gps_checks.cpp
EKF/vel_pos_fusion.cpp

This PR allows ECL to fuse velocity measurements from an external vision sensor such as the Realsense T265. In addition, it also improves on the external vision position fusion, such that the external vision measurement fusion is no usable with several EKF_AID_MASK configurations. 
Supported configuration for the EKF_AID_MASK are:
1      -     GPS
73    -     GPS + EV_POS + ROTATE_EV (incremental ev pos fusion, not recommended, use EV_VEL instead)
321  -     GPS + EV_VEL  + ROTATE_EV (recommended)
24    -     EV_POS + EV_YAW
72    -     EV_POS + ROTATE_EV
272  -     EV_VEL + EV_YAW
320  -     EV_VEL + ROTATE_EV
280  -     EV_POS + EV_VEL + EV_YAW
328  -     EV_POS + EV_VEL + ROTATE_EV
If you use no GPS information, you are now free to decide if you want your EKF reference frame to be …

External vision velocity

---

EKF/matlab/EKF_replay/Common/convert_px4_actuators_csv_data.m
EKF/matlab/EKF_replay/Common/convert_px4_groundtruth_csv_data.m
EKF/matlab/EKF_replay/Common/convert_px4_sensor_combined_csv_data.m
EKF/matlab/EKF_replay/Common/convert_px4_vehicle_gps_position_csv.m
EKF/matlab/EKF_replay/px4_replay_import.m
EKF/matlab/EKF_replay/readme.txt

fixes #595.
Because [EKF/matlab/EKF_replay/Common/convert_px4_sensor_combined_csv_data.m ](https://github.com/PX4/ecl/blob/master/EKF/matlab/EKF_replay/Common/convert_px4_sensor_combined_csv_data.m) will not use one timestamp and relative times any more, multiple timestamps are needed. So you need to be careful about the timestamps while importing the data from the CSV file.
Therefore I created a new MATLAB script, which imports all CSV files and converts them into the MATLAB data files.
Additionally you can convert ground truth data and the actuator controls/ actuator outputs. But this is all optional.
The new MATLAB script can also be called from the command line or a bash script like this:
```
#!/bin/bash
$matlab_bin="/path/to/matlab_binary"
$matlab_bin -batch "\ …
```

fix #595 and add new all-in-one conversion script (PX4 only)

---

EKF/airspeed_fusion.cpp
EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.cpp
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/gps_checks.cpp
EKF/gps_yaw_fusion.cpp
EKF/mag_fusion.cpp
EKF/sideslip_fusion.cpp
ecl.h

which is helpful for EKF replay debugging.
@priseborough Is `_imu_sample_delayed.time_us` the right time to stamp the messages?

Add timestamp to ECL print statements,

---

EKF/common.h
EKF/control.cpp
EKF/ekf.h
EKF/mag_fusion.cpp

This PR intends to improve yaw / magnetic field vector estimation for setups where the quality of the magnetomter Z component is bad. This is e.g. the case when there is a strong coupling between motor current and magnetometer Z measurement.
If this feature is enabled and the global position on earth is known then the estimator will calculate the magnetometer Z component based on the knowledge of the direction and strength of the magnetic field vector.
The synthesized component is used for the heading fusion but not for the 3D fusion. In the 3D fusion we rely on the x/y components of the magnetometer measurement to estimate the 3D magnetic field vector.
**Follow up work**
1) Since we don't fuse the synthetic Z measurement for 3D fusion we need to make sure to disable the mag Z bias state. …

implemented synthesized magnetometer Z measurement

---

EKF/control.cpp
EKF/ekf.h
EKF/mag_fusion.cpp

Fixes https://github.com/PX4/ecl/issues/627
Tested using replay log:
Before change log: https://logs.px4.io/plot_app?log=d1023af3-5b3c-43e2-a7e6-c3e7362af495
The yaw angle continued to drift when on ground
Quaternion variance continues to grow - if left unchecked this will eventually destabilise the filter
After change log: https://logs.px4.io/plot_app?log=d4591d33-40c6-4fd2-bd99-a892f2a308d6
Yaw doesn't drift
Quaternion variance when resting on ground doesn't continue to grow:
Short flight test of changes here: https://logs.px4.io/plot_app?log=eb89707c-d3b9-4175-8806-8e01d5d6f9ae

EKF: Fix on ground yaw drift when using EKF2_MAG_TYPE = 4

---

EKF/control.cpp
EKF/ekf.h

Just because it took me way too long to read this function.
After this refactor, the comment at the top of the function is almost redundant, should we remove it?

control: refactor rangeAidConditionsMet function

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
EKF/terrain_estimator.cpp

Ground clearance is the best estimate we can have when we are on the ground and we should not rely on a distance sensor that could output bad data before flight. 
This also helps when the drone is carried over as it avoids starting with a crazy downward distance for optical flow scaling.
The `dist_bottom` starts at 3 meters because it initializes on wrong range finder data.
The `dist_bottom` starts from the ground clearance and reject properly measurements until they actually make sense.

[Terrain estimator] Continuously reset terrain height on ground using known ground clearance

---

EKF/drag_fusion.cpp
EKF/ekf.cpp
EKF/ekf_helper.cpp
EKF/gps_yaw_fusion.cpp
EKF/mag_fusion.cpp
EKF/optflow_fusion.cpp
EKF/sideslip_fusion.cpp
EKF/terrain_estimator.cpp

This change fixes the following issues:
1) The quat_to_invrotmat function produced the same rotation matrix as the math library operator, but the name and comments indicated otherwise. This function was being used in several places where the math library could be used instead.
2) In several places where an inverse rotation was required, the rotation matrix was being calculated, then transposed.
The following changes have been made
1) Wherever the required rotation matrix can be calculated directly from the quaternion using the math library operator, this is done.
2) The quat_to_invrotmat function has been modified so that it outputs the inverse rotation to that produced by the math library and the comments have been updated to make this clear.
2) Wherever an inverse rotation matrix is …

EKF: Use math library for quaternion to rotation matrix conversions

---

EKF/CMakeLists.txt
EKF/common.h
EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/range_finder_checks.cpp
EKF/terrain_estimator.cpp

This PR attempts to cleanup the checks on the range finder data. Additionally it adds a hysteresis to declaring range finder data valid after signal quality was zero.
Specifically:
- whenever signal quality of the range data was 0 we require non-zero signal quality for 3 seconds before we accept the data to be used. This is to improve robustness against a known sensor failure mode where the signal quality toggles between 0 and non-zero values (see plot below)
- moved range finder data checks to a central location and created new file range_finder_checks.cpp in order to avoid loading control.cpp
- replaced _rng_hgt_faulty with _range_hgt_valid in order to avoid negation all over the place
- use better function name
- moved updateRangeDataContinuity() out of the terrain estimator and into …

Enhancement: Increased robustness against 0 signal quality and cleanup range data handling

---

Jenkinsfile

Purpose: have the containers updated with the current tags. Also, using the `px4-dev-ecl` container doesn't make sense anymore, as it just brought Python dependencies as an extra (https://github.com/PX4/containers/pull/208 removes that container).

Jenkins: update container tags; use px4-dev-base-bionic

---

EKF/ekf.cpp
EKF/ekf.h
EKF/estimator_interface.h

I'm creating a logic in PX4/Firmware that checks for motion an resets the states or completely the EKF. To do so, I needed to increase the granularity of the init function.
I also need to know if the vehicle is at rest or not so I created a getter to reuse the "at_rest" variable of EKF2.
Required for https://github.com/PX4/Firmware/pull/13346

Add access to EKF state reset

---

EKF/common.h

`bool` isn't supported
required for https://github.com/PX4/Firmware/pull/13433

parameters: change check_mag_strength from bool to int32_t to comply with the standard interface

---

EKF/python/wind_cov_init/derivation.py

This script derives the initial convariance matrix of the earth horizontal wind vector.
@CarlOlsson I was working on this to improve the initialization of the wind_estimation library we are using for airspeed fault detection. I noticed that you did something similar in #615 
@priseborough commented about the option to explicitly include the sideslip angle.
I think the derivation I did here could go into that direction.
When I set the yaw angle to 0 and both yaw and sideslip angle uncertainties to 0 I have 0 initial uncertainty in east direction. As soon as I have non-zero value for either yaw or sideslip uncertainty I see the contribution in east direction.
I've also tested the option to include the uncertainty of the ground speed in the derivation. However, using common variances for vx …

added python script for derivation of initial wind covariance matrix

---

ecl.h
test/test_EKF_basics.cpp
test/test_EKF_imuSampling.cpp
test/test_EKF_ringbuffer.cpp
test/test_EKF_sampling.cpp
validation/data_validator.h

The NuttX c++ library is incomplete, let's avoid including <cmath> until we have a real standard library in place.

remove <cmath> usage

---

EKF/common.h
EKF/gps_checks.cpp
test/test_EKF_basics.cpp

As the TDOP is usually not available from the GNSS receivers, GDOP cannot computed. As a replacement, the position dillution of precision (PDOP), which is a combination of VDOP and HDOP can be computed as follows:
```
PDOP = sqrt(VDOP^2+HDOP^2)
```
(required by https://github.com/PX4/Firmware/pull/13515)

Check PDOP instead of GDOP

---

EKF/common.h
EKF/control.cpp
EKF/covariance.cpp
EKF/drag_fusion.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
EKF/optflow_fusion.cpp
EKF/terrain_estimator.cpp
EKF/vel_pos_fusion.cpp

This PR is exactly the same as: https://github.com/PX4/ecl/pull/652,
but added as a separate branch to ECL. Such that we can test the PR's compatibility with the Firmware's CI.

[continue:] Moving towards multi-sensor-per-same-measurement fusion

---

EKF/ekf.cpp
EKF/ekf.h
EKF/gps_checks.cpp

This PR removes three obsolete code pieces during filter initialization. 
1) There was a `_ev_counter` counting incoming vision samples. It was never used.
2) An IF statement is checking the for the `ev_yaw` flag during initialization. The `ev_yaw` flag can not be true before entering the `controlFusionMode()` function, which happens only after successful initialization.
3) We allowed to initialize to vision height directly during initialization. This is not necessary, since the same switch to vision height will happen [here](https://github.com/PX4/ecl/blob/master/EKF/control.cpp#L1116).
4) An IF statement is checking the for the `rng_hgt` flag during initialization. The `rng_hgt` flag can not be true before entering the `controlFusionMode()` function, which happens only after successful …

Remove obsolete code in "initialiseFilter"

---

EKF/airspeed_fusion.cpp
EKF/common.h
EKF/control.cpp
EKF/covariance.cpp
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/gps_checks.cpp
EKF/gps_yaw_fusion.cpp
EKF/mag_fusion.cpp
EKF/sideslip_fusion.cpp

This PR removes the unnecessary EKF prefixes in most of the logged ECL messages. The EKF information is added per default in front of every ECL message, which can be seen here:
**Before:**
In addition it improves some of the comments.

Remove dublicated EKF prefixs from logged ECL messages

---

EKF/ekf.cpp
EKF/ekf.h
EKF/estimator_interface.h

The `resetStates()` function did a reset to a unit quaternion.  This is only wanted during a complete reset, together with setting the flag `_filter_initialised` to false. This triggers  than a new tilt and heading alignment.
With this PR I suggest to remove the resetStates(AndCovariances) functions and put their code directly in to their only caller. 
This helps to then to add a new reinitialize method. @bresch

Remove resetStates(AndCovariances) functions

---

EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/estimator_interface.cpp

The EKF is using accel measurements to initialize pitch and roll. Under the assumption that we are not moving, the accel measurement contains the gravity vector.
**Changes:**
To robustify against noise we previously average all the accel measurement over the period we wait for enough mag and baro measurements.This PR removes this averaging approach with a lowpass filter approach. The used filter is the usual 0.1/0.9 digital lowpass filter.
**Testing**:
I compared the time for successful tilt alignment in EKF replay to current master. There is no noticeable difference. The used log is recorded under soft motion. I also tested if it aligns under rough motion and it does. See log here:
https://review.px4.io/plot_app?log=3bf47850-4009-4793-9018-60fa10d82c7b
**Outlook:**
This will be needed …

Tilt Initialisation: Average Filter -> LowPass Filter

---

EKF/common.h
EKF/control.cpp
EKF/estimator_interface.cpp
test/CMakeLists.txt
test/sensor_simulator/CMakeLists.txt
test/sensor_simulator/baro.h
test/sensor_simulator/ekf_wrapper.cpp
test/sensor_simulator/ekf_wrapper.h
test/sensor_simulator/flow.cpp
test/sensor_simulator/flow.h
test/sensor_simulator/gps.cpp
test/sensor_simulator/gps.h
test/sensor_simulator/imu.cpp
test/sensor_simulator/imu.h
test/sensor_simulator/mag.cpp
test/sensor_simulator/mag.h
test/sensor_simulator/range_finder.cpp
test/sensor_simulator/range_finder.h
test/sensor_simulator/sensor.h
test/sensor_simulator/sensor_simulator.cpp
test/sensor_simulator/sensor_simulator.h
test/test_EKF_basics.cpp
test/test_EKF_fusionLogic.cpp

This PR adds several things:
- **Adds the EkfWrapper class** that has a pointer to an EKF object
It provides utility function for testing. Such as for example a `Vector3f getPosition()` function
- EKF_basic.cpp tests are updated to use EkfWrappers utility functions
- **RangeFinder and Flow sensor is added to the SensorSimulator class**
- Step functionality in GPS position.
- **Adding first sensor fusion logic tests** in `test_EKF_fusionLogic.cpp`
- fixes several lying comments and adds a few TODO comments

Expand test framework and test cases

---

EKF/ekf.cpp
EKF/ekf.h

This is a non-functional refactor in the initialiseFilter function. 
**Funny:**
`_rng_filt_state` was never used :)
**Testing:**
Any logic error should be covered by the *initialControlMode* unit test in CI. 
Additionally, EKF replay on recorded log is showing unchanged EKF alignment

Clean initialiseFilter function

---

EKF/control.cpp
EKF/ekf.cpp
EKF/ekf_helper.cpp
test/CMakeLists.txt
test/sensor_simulator/ekf_wrapper.cpp
test/sensor_simulator/ekf_wrapper.h
test/sensor_simulator/sensor_simulator.cpp
test/sensor_simulator/sensor_simulator.h
test/test_EKF_basics.cpp
test/test_EKF_initialization.cpp

With the current sensor sampling rates in the simulation, the tilt initialization is happening roughly after 0.42 seconds. 
The added checks are running for 0.5 seconds with simulated sensor data of different orientations. Edge cases such as pitch or roll = 90 degrees are covered.
On top, some random improvements went into this PR. Let them surprise you while you are doing the review.

Expands test to include initialisation of the orientation

---

CMakeLists.txt
EKF/common.h
EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/gps_checks.cpp
EKF/mag_control.cpp

This PR contains three cleanups:
1) Some variables containing the acronym *mag*  for magnitude are renamed to avoid confusion.
On top, some class variables are relocated.
2) Once we acquire a Gps location we can compute the earth rotation vector in our local coordinate system. This was done in the `predictState()` function. **Misplaced responsibility**. Porting this to gps_checks.cpp save one variable.
3) While on ground we check GPS signal for drift. Previously we had a variable for each component of the position derivative. This PR adds vector quantities to reduce number of variables, lines of code and increase the readability of the code.
SITL mission test: [Log](https://review.px4.io/plot_app?log=55106fda-c011-48ee-a8cf-7958e853fa64)

Random cleanup

---

EKF/common.h
EKF/control.cpp
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/mag_fusion.cpp
test/CMakeLists.txt
test/sensor_simulator/CMakeLists.txt
test/sensor_simulator/ekf_wrapper.cpp
test/sensor_simulator/ekf_wrapper.h
test/sensor_simulator/sensor_simulator.cpp
test/sensor_simulator/vio.cpp
test/sensor_simulator/vio.h
test/test_EKF_externalVision.cpp
test/test_EKF_fusionLogic.cpp

This PR add support to use all variance information in the visual_odometry message. It uses a 3d variance for position and velocity. Since we only fuse visual heading and not attitude, we do only support a one-dimensional uncertainty for the heading. 
Since external vision fusion in ECL is still fusing single measurement sequentially, we can not profit from the covariance values at the moment, so they are not added to the interface.
Secondly, the interface is expanded such that a 3D auxiliary velocity vector is passed instead of 2d vector. The vertical velocity is not fused at the moment. Since the control logic is not in place at the moment. This will be added, when we add finer fusion control granularity for all sensors.
See [here]() for the corresponding Firmware PR.
Unit tested cases: …

Support full vision variance 

---

EKF/CMakeLists.txt
EKF/common.h
EKF/ekf.cpp
EKF/ekf.h
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/imu_down_sampler.cpp
EKF/imu_down_sampler.hpp
test/test_EKF_imuSampling.cpp

This pulls out the down sampling of the IMU into a separate class. This is nice as we can hide a few variables inside the class.
Additionally it increases code readability introducing two new functions: `computeVibrationMetrics()` and `checkIfVehicleAtRest()`.
This increased the flash space by ~800 Bytes. Therefore I removed duplicated initialization of variable and reduced the number of repeatedly stored strings.
Current added flash space: 344 Bytes
**Testing:**
- Through unit tests and SITL mission test
- Flight tested in [here](https://github.com/PX4/Firmware/pull/13870)

Refactor imu downsampling

---

EKF/ekf.h
EKF/mag_fusion.cpp

This was dropped during the mag fusion refactor PR #662 
I directly added the check in `mag_fusion.cpp` since it is only used there. Is that fine for you @priseborough or this should absolutely not be done in case of 3D mag fusion selected by the user? (before, this check was only done when auto fusion was enabled but not in 3D fusion only)

mag_fusion: re-introduce delay between mag reset and fusion

---

EKF/control.cpp
EKF/range_finder_checks.cpp

The result of the "range stuck" detection logic was overriding the current validity of the range finder data. This means that even if the quality of the data is 0, if it is not "stuck", the validity was set to true.
@RomanBapst I think we messed it up in https://github.com/PX4/ecl/pull/655

range_finder_checks: fix validity flag

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/gps_yaw_fusion.cpp

This removes the IIR filter on the attitude offset between vision and EKF frame.
I don't see why this rotation would need to be low pass filtered. Especially if one of the two drifts, this leads to toilet-bowling.
Not sure if I did this right, so any review is appreciated.

Don't filter EV alignment

---

EKF/estimator_interface.cpp
EKF/estimator_interface.h

ECL should handle the down sampling the sensor data to match its limitation in buffer size. This PR brings the down sampling of the magnetometer data to ECL. Previously this was done on the Firmware side.
Related Firmware PR: https://github.com/PX4/Firmware/pull/13939
**Testing:**
Test flights: [logs](https://github.com/PX4/Firmware/pull/13944)

Move mag down sampling to ECL lib

---

EKF/common.h
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/gps_checks.cpp
test/sensor_simulator/airspeed.cpp
test/sensor_simulator/baro.cpp
test/sensor_simulator/gps.cpp
test/sensor_simulator/mag.cpp
test/sensor_simulator/range_finder.cpp
test/sensor_simulator/range_finder.h
test/test_EKF_measurementSampling.cpp

This PR contains several changes to the interface of ECL. The main goal is to standardize the interface. This is done by forcing all `set<Sensor>Data()` function to accept a `<Sensor>Sample`. Except from standardization this has the advantage that the pretty good documentation of the `<Sensor>Samples` function as part of the documentation of the interface.
Small remarks;
`gps_message` definition is adapted to profit from matrix:Vector
A legacy IMU interface from 2018 is also removed.
**Related Firmware PR:** https://github.com/PX4/Firmware/pull/13999

Updates to interface

---

EKF/covariance.cpp
EKF/matlab/scripts/Inertial Nav EKF/wind_cov.py

Update the initialization of the wind state covariance submatrix as discussed [here](https://github.com/PX4/ecl/issues/602)
Here is a SITL mission where the plane take off facing east and then turns to the north. Synthetic sideslip fusion is turned off
master/pr
As can be seen on the PR the initial wind uncertainty in east direction is lower than in north which makes sense.
@priseborough Compared to our precious discussion I did not set the wind along body y to zero in the covariance initialization. When looking through the derivation I simply did not see a reason for that, would be happy if you could review
The derivation is done using the following sympy script
```
import sympy as sp
Wx, Wy, yaw, R_TAS, initial_wind_var_body_y, R_yaw = sp.symbols('Wx Wy yaw R_TAS initial_wind_var_body_y …
```

EKF: update wind covariance initialization

---

.clang-format
.github/workflows/format_checks.yml
EKF/AlphaFilter.hpp
EKF/RingBuffer.h
Makefile
tools/format.sh

This PR brings auto-formatting with clang-format-6.0 to ECL. It adds a few Makefile targets, which provide installation of clang-format, checking the format and formatting the code.
The formatting rules are based on google style guide. Except for some indentation modifcation to stay closer to appearance of the Firmware. The following options were adapted:
```
AccessModifierOffset: -4
IndentWidth: 4
TabWidth: 4
UseTab: Always
```
The files on which the auto-formatting is required, is specified in tools/format.sh. At the moment it is only added for EKF/RingBuffer.h and EKF/AlphaFilter.hpp
A github action that checks if the format is according to the rules is also added.

Auto Formatting with clang-format-6.0

---

EKF/common.h
EKF/estimator_interface.cpp
EKF/estimator_interface.h
test/sensor_simulator/vio.cpp
test/sensor_simulator/vio.h

Previously ECL had two different structs containing external vision data: `ext_vision_message` and `extVisionSample`. The only difference is that the `ext_vision_message` does not have time field, as time is passed with `setExtVisionData(time, ext_vision_message)`.
This PR removes `ext_vision_message` and is changing the interface to  `setExtVisionData(extVisionSample)`, which is getting the time with the time field of the `extVisionSample`
**Related Firmware PR:** https://github.com/PX4/Firmware/pull/13989
**Testing:**
- it compiles
- ev unit tests are still passing

Update setExtVisionData interface

---

.github/workflows/build_tests.yml
.github/workflows/firmware_build_test.yml
.github/workflows/format_checks.yml
.github/workflows/unit_tests.yml

Previously the Firmware build tests check was not able to checkout the right ECL version on forks. Now it is.
Also were the github actions run twice for upstream branches. Once on push, once on the PR. With changing them to pull_request only. Now they will appear only once.

Fix github action to work with forks

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/gps_yaw_fusion.cpp

As suggest by @nicovanduijn and @bresch in https://github.com/PX4/ecl/pull/709, it is beneficial to remove the filtering on the vision reference frame alignment. Quickly changes in heading state due to magnetic interference was causing the toilet boiling as the filtering of the vision alignment introduced to delay. A VIO estimate is not really noisy, as it is most likely an output of an estimator itself, therefore it is reasonable to remove the filter on the alignment.
**Testing:**
@bresch do you still have a log?

Remove filtering on external vision alignment

---

EKF/estimator_interface.cpp

The range sample passed to the EKF was not actually used. This resulted in a negative timestamp and as a result range finder was never fused.
Signed-off-by: RomanBapst <bapstroman@gmail.com>

estimator_interface: bugfix, set range sample correctly

---

EKF/control.cpp
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/gps_checks.cpp

I had enough of reading those:
`_control_status.flags.opt_flow && !(_control_status.flags.gps || _control_status.flags.ev_pos || _control_status.flags.ev_vel)` `_control_status.flags.opt_flow && !_control_status.flags.gps && !_control_status.flags.ev_pos && !_control_status.flags.ev_vel)`
The functions are:
- isOnlyActiveSourceOfHorizontalAiding(flag) : if the flag passed is set but not the other ones
- isOtherSourceOfHorizontalAiding(flag) : if an other aiding is active than the one passed
for example: if `opt_flow` is true, all the following calls will return `true` regardless of their own state:
- isOtherSourceOfHorizontalAiding(_control_status.flags.gps)
- isOtherSourceOfHorizontalAiding(_control_status.flags.ev_vel)
- isOtherSourceOfHorizontalAiding(_control_status.flags.ev_pos)
- …

Ekf: use helper functions to centralize the checks of horizontal aiding

---

CONTRIBUTING.md

This updates the description of the `Firmware build tests`. To respect the changes made to the CI in https://github.com/PX4/ecl/pull/733

Update description of Firmware build tests

---

EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/gps_checks.cpp
EKF/terrain_estimator.cpp
test/CMakeLists.txt
test/sensor_simulator/ekf_wrapper.cpp
test/sensor_simulator/ekf_wrapper.h
test/sensor_simulator/gps.cpp
test/sensor_simulator/sensor_simulator.h
test/test_EKF_fusionLogic.cpp
test/test_EKF_gps.cpp

This PR solves the open issue on timestamp checks: fixes #459
The issue was previously addressed by lower-bounding the timestamp of incoming GPS and baro samples. This can potentially be dangerous as rather old data could be re-timestamped and still be used. By removing these lower bounds old data would enter the buffer as it is and would be rejected by the Ringbuffer [checks](https://github.com/PX4/ecl/blob/master/EKF/RingBuffer.h#L133).
The issue of comparing unsigned integers is solved by avoiding the subraction. e.g:
```
_time_last_imu > _time_last_gps + (uint64_t)10e6
```
There should be also no issue with overflows under the assumption that the interval is rather small
**Testing:**
- Added unit tests for starting and timing out major sensors
- SITL flight …

Robustify timestamp checks

---

EKF/common.h
EKF/covariance.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp

This issue was found by @RomanBapst during a git bisect search to find the cause of a growing Z delta velocity bias estimate and vertical position and velocity innovations
that had appeared with a hardware setup when the firmware was updated. This search determined that the issue was introduced by https://github.com/PX4/ecl/pull/689/commits/ea3f95a56486a274cc71b549176de8364eea40d5 in a PR that was supposed to be a non functional change.
Because the covariance initialisation is dependent on the quaternion states, the Ekf::initialiseCovariance() function must be called after the states are aligned, not before.
It is also unnecessary to call Ekf::initialiseCovariance() in the Ekf::reset() function because this function sets _filter_initialised to false which causes the …

Fix bug causing incorrect covariance initialisation

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/gps_yaw_fusion.cpp

As the name can be ambiguous, it gets renamed "uncorrelateQuatFromOtherStates".
Also replace the loops storing the values and reapplying them by simply
zeroing two slices (this also saves 130B of flash).

ekf: clean uncorrelateQuatStates function

---

EKF/ekf_helper.cpp

To obtain the correct difference between two angles, we need to wrap
the result between -pi and pi. Otherwise, the difference between two
angles close to 180 degrees but with opposite signs will produce a large
error.
For example if a = -179 and b = 179, b - a = 258 instead of -2 degrees

ekf: fix angle wrapping in realignYawGPS

---

EKF/ekf_helper.cpp

This PR removes a bug that was introduced [here](https://github.com/PX4/ecl/commit/4511b9ff5e0a75c6eb4912b813a62f23ea2cd707) 
In a velocity reset we only used the GPS measurement if `_gps_check_fail_status.value` was equal to zero. The value of this flag is independent of `EKF2_GPS_CHECK` so checks can fail even if they are not configured to have any effect. E.g. on PX4 v1.10.1 the check will always fail if the vehicle is using two GPS modules since the gdop field is set to infinity. (On master gdop is replaced by pdop which is set correctly since https://github.com/PX4/Firmware/pull/13515/files)
My interpretation is that the GPS checks configured to run by `EKF2_GPS_CHECK` and defined by the corresponding threshold parameters are *preflight* checks and should have no influence other than …

EKF: dont check gps_check_fail_status is velocity reset

---

.github/workflows/build_tests.yml
test/gtest.cmake
test/sensor_simulator/sensor_simulator.h
test/test_EKF_airspeed.cpp
test/test_EKF_imuSampling.cpp

This allows for the test also run with the Clang compiler.
@MaEtUgR You have added [this](https://github.com/PX4/ecl/pull/741/files#diff-59007f958bf3519ed464d95c410f5d1eL44) on the Firmware side. Do you know if this is still necessary? This caused issues with the Clang compiler.
I noticed that if the same code is compiled with Clang compiler, the change indication output differs from the one produced when compiled with GCC.
#740

Make test with Clang

---

EKF/ekf.cpp
EKF/ekf.h

Should fix https://github.com/PX4/ecl/issues/744
The code was missing sanity checking of the accel vector length and angular motion.
Has been tested on replay and passes checks. The accel and gyro thresholds should be able to be met on a moving platform such as a boat, but there will be some delay as it waits for the conditions to be met. Ground testing with movement is required to verify that the thresholds are appropriate. We can adjust on replay.

EKF: Don't allow alignment if vehicle is moving excessively

---

EKF/CMakeLists.txt
EKF/EKFGSF_yaw.cpp
EKF/EKFGSF_yaw.h
EKF/common.h
EKF/control.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
EKF/mag_fusion.cpp

Replaces https://github.com/PX4/ecl/pull/764.
Has been rebased.
See https://github.com/PX4/ecl/pull/764. for discussion and test evidence

EKF: Add Emergency yaw recovery using EKF-GSF estimator

---

EKF/control.cpp

Without this change the EKF will print
```
EKF baro hgt timeout - reset to GPS
EKF gps hgt timeout - reset to GPS
```
Directly after each other if the baro times out

EKF: dont print wrong reset message on baro timeout

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp

Summary:
- replace all the `isRecent(gps_newest.time_us, 2 * GPS_MAX_INTERVAL)` by `!_gps_hgt_intermittent`, because it is already computed here: https://github.com/PX4/ecl/blob/93be6ea49a22b08a4bc42010a7c537640eae09fc/EKF/control.cpp#L91-L92
replace all the `isRecent(baro_init.time_us, 2 * BARO_MAX_INTERVAL)` by `!_baro_hgt_faulty`, because it is already computed here: https://github.com/PX4/ecl/blob/93be6ea49a22b08a4bc42010a7c537640eae09fc/EKF/control.cpp#L88-L89
- remove the useless setControl...Height() when the fusion mode is alredy active: 
e.g.:
```c++
if(_control_status.flags.baro_hgt) {
...
setControlBaroHeight();
...
}
```
- extract the check of vertical velocity divergence due to accelerometer clipping to `checkVerticalAccelerationHealth()`
**Note** : it should be easy to …

Small height reset cleanup

---

EKF/covariance.cpp
EKF/ekf.h
EKF/ekf_helper.cpp

A complete and clean reset of the mag states covariances is now performed through the "resetMagCov"
function only. This avoid having slight differences of implementations across the code.
Log before this PR:
https://logs.px4.io/plot_app?log=f926bdca-989f-4f90-9483-0f3168660cd3
With this PR:
https://logs.px4.io/plot_app?log=ca6a418d-5da8-48ee-a636-e9d1bccd36b4

ekf2: centralize mag covariance reset

---

EKF/EKFGSF_yaw.cpp
EKF/EKFGSF_yaw.h

I just remembered that I found a nice generic equation to compute the accel gain for the AHRS (https://github.com/PX4/ecl/pull/751#discussion_r381228066)
https://www.desmos.com/calculator/dbqbxvnwfg
Replace the multiple if-else statements by a generic equation.
- For a multicopter, the attenuation factor is 2 and symmetrical
- For a fixedwing, the attenuation factor is 1 if the acceleration is positive and that centripetal correction is available and 2 otherwise.
Note that the function `sq` needs to be `const` in order to be used in a `const` function.

YawEst: simplify AHRS accelerometer gain computation

---

EKF/common.h
EKF/terrain_estimator.cpp

This adds the ability to select range finder and/or optical flow fusion for terrain estimate.
Reason: I need to disable optical flow fusion for terrain estimate on a multirotor.
Note that I wanted to use `enum class` but then I have to define all the operators used for bitmasks and it adds to much code boilerplate for little benefit.
Firmware PR: https://github.com/PX4/Firmware/pull/14427

Terrain estimator: Add sensor aiding bitmask

---

EKF/control.cpp

Fixes a bug that got introduced in https://github.com/PX4/ecl/pull/737
The offset needs to be updated directly when switching to range height.
Thanks to @hyonlim for finding the bug.

EKF: fix range height sensor offset

---

EKF/common.h
EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/gps_checks.cpp
EKF/mag_control.cpp
EKF/mag_fusion.cpp
EKF/terrain_estimator.cpp

Enables takeoff in a non-GPS flight mode with mag fusion type set to MAG_FUSE_TYPE_NONE. After sufficient horizontal movement the EKF will reset the yaw to the EKF-GSF estimate. After that occurs GPS fusion will commence and normal flight operations can commence.
This would enable operation where GPS quality is good, but magnetic field conditions do not allow use of a magnetometer. Examples include operation from ships or close to the earths magnetic poles.
Replay yaw data - the EKF yaw is 0 at initial alignment and is reset to the GSF estimate when the GSF yaw 1-sigma accuracy estimate drops below 15 degrees:
GPS velocity innovations - these are low after the reset indicating that it was a good yaw alignment:
If an optical flow sensor and range finder was fitted, the initial takeoff …

EKF: Enable GPS flight without magnetometer

---

EKF/airspeed_fusion.cpp
EKF/covariance.cpp
EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/terrain_estimator.cpp
test/sensor_simulator/ekf_logger.cpp
test/sensor_simulator/ekf_wrapper.cpp
test/sensor_simulator/ekf_wrapper.h
test/test_EKF_airspeed.cpp
test/test_EKF_basics.cpp
test/test_EKF_externalVision.cpp
test/test_EKF_fusionLogic.cpp
test/test_EKF_initialization.cpp

This PR contains several non-functional improvements regarding style:
- Replace some private float arrays with matrix::Vectors
- Change interface functions to output by return-by-value
- Add const modifier to getters
- Enforce camelCase in changed functions
The flash size is decreasing by roughly 250 Bytes for v4/v5 targets, but for v2 the flash is overflowing by a tiny bit.
During profiling a SITL mission flight, no significant performance difference has been detected.
This is changing the interface. It could be an option to keep the old interface and mark it as deprecated.
Firmware PR: https://github.com/PX4/Firmware/pull/14162
Testing:
- No functional change indicated
- FixedWind [Log](https://review.px4.io/plot_app?log=862caccc-2651-4703-bd9b-65e6406f6d52)
- Multicopter …

Interface style improvement

---

EKF/control.cpp
EKF/ekf_helper.cpp
EKF/sensor_range_finder.hpp
EKF/terrain_estimator.cpp
test/test_SensorRangeFinder.cpp

Following #782, we identified an inconsistency where the newest sample was used to initialize the terrain estimator instead of the delayed -and verified- measurement (fixed in https://github.com/PX4/ecl/commit/45de501e19a2bf866bfbc60b48d96683b24f43b2 ).
Additionally, in https://github.com/PX4/ecl/commit/b4f35d47bf95c3832446ce5ac085b09ab6ad154a I added the `distBottom` function to the `SensorRangeFinder` class to directly get the vertical measured distance below the drone, corrected for tilt.
**Please answer** https://github.com/PX4/ecl/pull/792/files#r402776911

TerrainEstimator initialization fix

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/gps_checks.cpp

When the primary height source is GPS but the GPS data times out, EKF2 switches to baro and makes a reset. However, the `_hgt_sensor_offset` was not set to 0 and the height reset creates an incorrect jump in the state.
partially fixing https://github.com/PX4/Firmware/issues/14677

Fix baro fail-over in GPS hgt mode

---

test/test_EKF_externalVision.cpp
test/test_EKF_flow.cpp
test/test_EKF_gps.cpp
test/test_helper/CMakeLists.txt
test/test_helper/reset_logging_checker.cpp
test/test_helper/reset_logging_checker.h

This is a follow up to the velocity reset refactoring in https://github.com/PX4/ecl/pull/788. I now added also tests for the correct storing of the reset -deltas/-counters. Those are important for the position/velocity controller, as they are used for control.

Add tests for velocity reset logging

---

CMakeLists.txt
EKF/AlphaFilter.hpp
EKF/ekf.cpp
EKF/ekf.h
EKF/estimator_interface.h
test/test_AlphaFilter.cpp

For the battery filter time abstraction in PX4 https://github.com/PX4/Firmware/pull/14551/ I implemented the same filter there and am now merging the two versions here.
It's the best of both sides I think except I couldn't do the NAN checks because `matrix::Vectors` do not support `isfinite` checks. So I have to take care with the PX4 callers that they never run NAN through the filter.
Sidenote: While working with the unit tests I missed the gtest colors so I added them with `GTEST_COLOR=1` like in PX4.

Alpha filter merge with PX4 version

---

CMakeLists.txt
EKF/ekf.h
EKF/ekf_helper.cpp
test/sensor_simulator/gps.cpp
test/test_EKF_externalVision.cpp
test/test_EKF_fusionLogic.cpp
test/test_EKF_gps.cpp

This PR contains:
- refactor resetPosition()
- use new assignment operators from matrix library during velocity and position resets
- fix horizontal GPS position step functionality in sensor simulator's GPS sensor.
- Add unit tests for reset to GPS and vision position.
When bringing this to the Firmware the newest Matrix library is needed: https://github.com/PX4/Matrix/commit/d613055462bcbeacfd188cbd53de56c1dbc7b94d
TODO:

Refactor resetPosition

---

EKF/RingBuffer.h

Subtraction of two unsigned integers can be dangerous. I think in this case it does not really matter, but it is better to be safe.

Avoid subtraction of two uint inside RingBuffer

---

EKF/control.cpp
EKF/ekf.h

Fixes https://github.com/PX4/ecl/issues/804
Testing was performed using jmavsim SITL. Log here: https://logs.px4.io/plot_app?log=141aa81d-6ea4-411e-9f89-4387dd6ca1c4
The following steps were performed:
1) Takeoff in ALTCTRL and climb to approx 5m
2 Perform a series of horizontal maneouvres for 15 seconds to ensure GSF yaw was fully aligned.
3) Turn off GPS using SIM_GPS_BLOCK = 1
4) Turn GPS back on using SIM_GPS_BLOCK = 0 when the stopping navigation message was received.
5) Verify GPS position and velocity states are reset and no yaw reset is performed.
Console messages:
Velocity and position states:
Yaw:

Fix EKF does emergency yaw reset after intermittent gps data

---

CMakeLists.txt

- stay in sync with PX4/Firmware
This doesn't really change anything, just keeping it consistent with PX4/Firmware.

cmake update CXX standard 11 -> 14

---

EKF/control.cpp

What would we do without the lower bound protection?

Fix ev_pos_obs_var(1) entry

---

EKF/ekf.h
EKF/ekf_helper.cpp

This is splitting up the `resetVelocity` into smaller parts. This is making the intention of the `resetVelocity` function more clear and will help in the future to command a velocity reset to a specific sensor from else where in the code.

Refactor velocity resets

---

EKF/control.cpp

The `resetQuatStateYaw` function is already providing the functionality for resetting the yaw to a certain angle.
Would be cool, if this is merged together with the [vision velocity in body frame](https://github.com/PX4/ecl/pull/708), since it will profit from this flash size reduction.

Remove duplicate code during vision yaw reset

---

EKF/common.h
EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/gps_checks.cpp
test/sensor_simulator/vio.cpp
test/sensor_simulator/vio.h
test/test_EKF_externalVision.cpp

At the moment we expect the external vision's velocity to be expressed in world/local frame. This PR allows for the vision velocity also being expressed in body frame. For this an enum is added to the vision sample that stores the information about the used velocity frame.
VIO systems that output velocity in body frame do not rely on its orientation data to be correct or existing to transform the velocity frame to world coordinates. Instead we can directly transform the velocity to ekf's local frame by using the ekf's quaternion state.
**Testing:**
- Expanded unit tests to check if we can can fuse velocity in body and local frame
- Fly tests: [EV_VEL only](https://review.px4.io/plot_app?log=e43feac7-7f21-4bbf-8dc4-54ab0da1f002), [GPS & …

Support vision velocity expressed in body frame too

---

EKF/airspeed_fusion.cpp
EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.h
EKF/gps_checks.cpp
EKF/gps_yaw_fusion.cpp
EKF/mag_fusion.cpp
EKF/sideslip_fusion.cpp

This is reducing the flash size by roughly 470 bytes.
The draw back is that some of those messages are not printed with a timestamp to the "SITL" terminal.
Firmware build tests are failing since ECL master is not compatible with Firmware master at the moment

Reduce stored strings, to save flash space

---

EKF/control.cpp

See https://github.com/PX4/ecl/issues/786 for description of problem
This fixes the failure case where if GPS quality resulted in GPS pre-flight checks failing, no height sensor was used. The intended behaviour is now:
1) Once GPS height use commences, it will continue to be use provided 3D fix data is available. 
2) If range finder is being used as part of the user selectable 'range aid' functionality (uses range finder when low and slow), then switch back to using GPS height does require quality checks to pass. This is because GPS glitches combined with use of GPS height at low altitude is undesirable. If GPS quality checks do not pass then baro will be used as a backup. Using baro as a backup may be something that is undesirable for some vehicles.
3) If using baro and GPS checks pass, …

Fix GPS altitude not fused if GPS checks fail and GPS is primary height source

---

EKF/covariance.cpp
EKF/ekf.h
test/test_EKF_initialization.cpp

This is a non-functional change required to select accel bias estimation per axis selection. The intent is then to disable the learning before takeoff of the components that are poorly observable.

ekf: split accel bias learning in independant xyz components

---

EKF/ekf_helper.cpp
test/test_EKF_fusionLogic.cpp

Alternative solution to https://github.com/PX4/ecl/pull/819.
> The _deadreckon_time_exceeded flag is used in local_position_is_valid(). This means that
_params.valid_timeout_max after startup, in my observed case 5 seconds, the local position switches from valid to invalid and then after a while back to valid again. @julianoes 
Since the local position flag is also responsible for entering into position control mode, the initial value should be false in my opinion. Otherwise take off in position control could be possible even tough there is no observation constraining the state. 
Only after a first aiding event we should allow it to get valid until the aiding gets timedout eventually.
SITL log:
Before
After

EKF: fix initialization of local position validity 2

---

EKF/gps_yaw_fusion.cpp
test/CMakeLists.txt
test/sensor_simulator/ekf_wrapper.cpp
test/sensor_simulator/ekf_wrapper.h
test/sensor_simulator/gps.cpp
test/sensor_simulator/gps.h
test/test_EKF_gps_yaw.cpp

This is probably not completely non functional, since there was a check whether the reset should happen  based on the quaternion error.
Now this check is based on the absolute yaw delta. The value of 15 degrees is still the same, not sure if this should be changed.

Use resetQuatStateYaw during gps yaw reset

---

EKF/gps_yaw_fusion.cpp

Found in https://github.com/PX4/Firmware/pull/14940.

EKF: resetGpsAntYaw() fix double promotion

---

EKF/common.h
EKF/control.cpp
EKF/ekf.h

**Problem**
Currently the main EKF will only make use of the yaw estimator if a gps fusion timeout happens within 30 seconds after takeoff. Given that the estimator works quite well we should enable it always as it could save the vehicle in the case of a mag failure (broken cable, mag coming loose, ...)
**Solution**
This change enables a yaw reset later in flight but  with some limitations:
- The criteria is modified, requiring a complete loss of position and velocity observation for the current nav reset interval
- The total number of resets is limited to 3.
- Resets can't be less than 5 seconds apart
- Resets won't be performed if GPS signal has been lost in the immediate past
- Resets won't be performed if the loss of navigation preceded commencement of flight (we may need to modify …

EKF: Allow reset of yaw to EKF-GSF later in flight

---

EKF/vel_pos_fusion.cpp

Before fusing velocities and position information an innovation check is performed. Previously for position there was an additional tilt align check. This is not necessary as for all position sources a tilt-align check is performed before starting the fusion. There is also no reason why it would be necessary for the position check, but not for the velocity(-in-world-frame) check.

Remove tilt align from position innovation check

---

EKF/EKFGSF_yaw.cpp
EKF/EKFGSF_yaw.h
EKF/ekf_helper.cpp

The EKF-GSF yaw estimator uses a bank of AHRS filters that are unable to estimate rate gyro bias about the gravity vector. This can result in poor yaw estimates when large yaw gyro bias errors are present before takeoff. This is the effect of a 0.05 rad/sec yaw rate bias applied in SITL:
After application of the patch, yaw drift during hover is corrected:

EKF: Reduce EKF-GSF vulnerability to large yaw gyro bias errors

---

EKF/ekf.h
EKF/estimator_interface.cpp
EKF/imu_down_sampler.cpp
EKF/terrain_estimator.cpp
EKF/vel_pos_fusion.cpp
test/CMakeLists.txt
test/sensor_simulator/ekf_wrapper.cpp
test/sensor_simulator/ekf_wrapper.h
test/sensor_simulator/flow.cpp
test/sensor_simulator/gps.cpp
test/sensor_simulator/gps.h
test/test_EKF_flow.cpp
test/test_EKF_terrain_estimator.cpp

I tried to split the fixes properly in different commits.
Summary of the fixes:
- possibility to choose the aiding sources of the terrain estimator
- ~get feedback in the log from the aiding sources currently used by the terrain estimator (will require Firmware update to actually log the data)~ edit: moved to #839
- ~fix sensor simulator that was updating the ekf faster than IMU data (this created instability of the filter in dynamic unit tests) FYI @kamilritz~ edit: moved to #838
- add unit tests for flow and range fusions in the terrain estimator
~Due to the `sensor_simulator` update rate fix, a lot of unit tests are now failing (because EKF prediction step runs slower) and I'm currently fixing them.~ edit: fixed in #838

Terrain fusion aid selection fix

---

EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/gps_checks.cpp

In SITL the gps reference altitude was always set to zero as the gps checks passed before the main filtered initialized.
This PR also sets the gps velocity and position derivative filter states to zero if they are not being updated (vehicle is in air or there is movement.)

Fix GPS reference altitude in case gps checks pass quickly

---

EKF/AlphaFilter.hpp

fixes https://github.com/PX4/Firmware/issues/15065
The denominator of `setParameters()` can get zero if `time_constant` and `sample_interval` both are exactly zero. In this case updating the filter coefficient needs to be prevented.

AlphaFilter: prevent setParameters division by zero

---

EKF/CMakeLists.txt
EKF/EKFGSF_yaw.cpp
EKF/EKFGSF_yaw.h
EKF/drag_fusion.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
EKF/mag_fusion.cpp
EKF/optflow_fusion.cpp
EKF/sideslip_fusion.cpp
EKF/terrain_estimator.cpp
EKF/utils.cpp
EKF/utils.hpp

This extracts three functions that do not need access to any ekf class member into a utils file.
These functions are:
```
Dcmf EKFGSF_yaw::taitBryan312ToRotMat(const Vector3f &rot312) ;
float kahanSummation(float sum_previous, float input, float &accumulator); 
Matrix3f quat_to_invrotmat(const Quatf &quat) 
```
By doing so we can avoid defining the taitBryan312ToRotMat twice.
`quat_to_invrotmat` got renamed to `quatToInverseRotMat` and the return type got specified to `matrix::Dcmf`.

Extract general functions into utils

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/gps_yaw_fusion.cpp
EKF/mag_control.cpp
test/sensor_simulator/ekf_wrapper.cpp
test/sensor_simulator/ekf_wrapper.h
test/sensor_simulator/gps.cpp
test/sensor_simulator/gps.h
test/test_EKF_gps_yaw.cpp

Summary of the changes:
- always reset yaw estimate when starting GPS yaw fusion
- This is done because otherwise, if close to the limit (15 degrees), a large gyro bias can be learned and it takes a loooong time for the estimate to converge to the yaw GPS value
- disable GPS yaw fusion if there is no yaw data in the GPS message, if the fusion is rejected or if disabled by the user. The estimator will automatically fall back to another source of yaw aiding if possible (e.g.: mag fusion if enabled).
- add unit tests
non-functional change:
- do not check if the GPS yaw data is nan in the fusion function but only in `control.cpp`

GPS yaw improvements

---

CMakeLists.txt

This is part of what is required for using `bloom` to generate packages on the ROS buildfarm
Signed-off-by: Bill Morris <bill@sevendof.com>

Provide alternative to `git` introspection for version information

---

.github/workflows/firmware_build_test.yml

At the moment Firmware build checks fail on pull requests from forks. I hope this is change is indeed enough.

Attempt to fix CI firmware build test

---

EKF/control.cpp
EKF/ekf.h
EKF/gps_yaw_fusion.cpp
test/sensor_simulator/gps.cpp
test/sensor_simulator/gps.h
test/test_EKF_gps_yaw.cpp

When the antennas are not parallel to the x body axis, the GPS message contains the angular offset but the data is already corrected in the driver. EKF2 should then not add this offset during the initialization.
I also added unit tests with different initial orientations and antenna offsets.

GPS Yaw: fix heading initialisation and add unit tests

---

EKF/control.cpp

For each sensor we keep the timestamp of the latest measurement in the buffer. This timestamp is used to not push data in the buffer to often, which would lead to a lose of measurements.
Surprisingly, the `_time_last_gps` timestamp was updated with the imu timestamp once when we start the GPS fusion. I think this is not correct and should be removed.

Do not update time_last_imu outside of setGpsData

---

.github/workflows/firmware_build_test.yml

It seems that I finally got it.
There is a [race condition in the Github checkout action v1](https://github.com/actions/checkout/issues/23#issuecomment-553994987), which likely caused the issue.
This PR uses the newest version of the checkout action. But for creating a local git repository during the checkout a git version >2.18 is now necessary. Therefore the dev-base-focal container needs to be used.

Fix firmware-build-test

---

AlphaFilter/AlphaFilter.hpp

I forgot to include `float.h` in https://github.com/PX4/ecl/pull/843 when using `FLT_EPSILON`.
Not sure why nothing ever complained until I used it recently.

AlphaFilter: include float.h for FLT_EPSILON

---

EKF/control.cpp

This is the only place where we use the alignOutputFilter function after a reset. We update the position and velocity states of the output_buffer already inside the reset functions above.
alignOutputFilter does also update the quaternion state, but I see no need for this inside the flow fusion.

Do not update output filter a second time after reset to flow.

---

.github/workflows/firmware_build_test.yml

Extend firmware build checks to check if the resulting firmware will fit on fmu-v2. If this is only noticed once it is brought to the Firmware, it can be a blocker.

Extend firmware build checks

---

geo/geo.cpp
test/test_geo.cpp

Previous 2D (and 3D) projection functions I've worked with have all responded to negative distance with as being in the opposite of the positive distance. Up for discussion whether this should be changed.
(part of my demo for the dev summit)

Negative distances go in the opposite direction

---

geo/geo.cpp
test/test_geo.cpp

Needed for merging into Firmware, other wise we get compiler error for implicit conversion.

Make conversion from float to double explicite

---

EKF/gps_yaw_fusion.cpp
EKF/python/ekf_derivation/generated/gps_yaw_fusion_generated_compare.cpp
EKF/python/ekf_derivation/generated/gps_yaw_generated.cpp

This PR replaces the Matlab generated equations with sympy generated equations. Continues on from #870.
Modifies the methods used for fusion of GPS receiver yaw angle.
Includes comparison test scripts that compare the observation Jacobians and Kalman gain equations generated for the Matlab symbolic toolbox and SymPy.
**Testing**
gps_yaw_fusion_generated_compare.cpp output:
Pass: GPS yaw Hfusion max diff fraction = 1.796981e-07
Pass: GPS yaw Kfusion max diff fraction = 3.981467e-07
SITL testing TODO

EKF: Convert GPS yaw observation method to use SymPy generated code

---

EKF/gps_yaw_fusion.cpp
EKF/mag_fusion.cpp

Uses ecl powf function for instances of powf that have an integer exponent

EKF: use ecl::powf for integer exponents

---

EKF/airspeed_fusion.cpp
EKF/python/ekf_derivation/generated/tas_fusion_generated_compare.cpp
EKF/python/ekf_derivation/generated/tas_generated.cpp
EKF/python/ekf_derivation/generated/util.h

Replaces matlab symbolic toolbox generated equations with equivalents generated using the SymPy library.
The following innovation and innovation variance sequence was generated from replay of a gazebo_plane SITL log. The sequences are visually identical.
Before:
After:
Output from the test program comparing the Jacobians and Kalman gain values from the Matlab and SymPy method is shown below. Differences are within the expect range for single precision operations.
Pass: Airspeed Hfusion max diff fraction = 0.000000e+00
Pass: Airspeed Kfusion max diff fraction = 3.226521e-07

EKF: Convert airspeed fusion to use SymPy generated auto-code

---

EKF/ekf.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h

It helps to look at commit it by commit.
The `output_*_delayed` states are used to compute the correction that gets applied to the output filter, such that the `output_*_delayed` states are tracking the EKF delayed states.
It seems that it is not necessary to have a member variable to store this delayed output. Storing it only introduces the need to keep it in sync with the buffer itself, during a EKF state reset.
In addition, I notice that we get the delayed output by calling the buffers `get_oldest` function. Will the oldest entry in the buffer always be close to the delayed fusion horizon?
Plus, in the alignOutputFilter, the output_new's quaternion gets updated, but not its velocity or position. Bug?

Make delayed output state non-member variable

---

EKF/drag_fusion.cpp
EKF/python/ekf_derivation/generated/acc_bf_fusion_generated_compare.cpp
EKF/python/ekf_derivation/generated/acc_bf_generated.cpp

Before and after innovations, innovation variances and wind state estimates from replay of gazebo SITL log data with EKF2_AID_MASK set to 33 to activate drag fusion.
Before:
After:
Output from the auto-code comparison test program shows expected amount of difference between Matlab and SyPmy generated code:
Pass: Specific Force X axis Hfusion max diff fraction = 0.000000e+00
Pass: Specific Force X axis Kfusion max diff fraction = 1.161862e-06
Pass: Specific Force Y axis Hfusion max diff fraction = 0.000000e+00
Pass: Specific Force Y axis Kfusion max diff fraction = 2.331720e-06

EKF: convert drag fusion from Matlab to SymPy generated auto-code

---

EKF/EKFGSF_yaw.cpp
EKF/airspeed_fusion.cpp
EKF/covariance.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/mag_fusion.cpp
EKF/utils.cpp
EKF/utils.hpp
test/test_EKF_utils.cpp

This PR adds multiple helper functions related to heading computation. It contains helper functions to compute a heading with either 321 or 312 rotation sequence, and more ...
Best to review commit by commit.

Yaw helper functions

---

EKF/mag_fusion.cpp

There is no need to check if 3d fusion is active when in mag heading fusion mode since this is impossible.

mag_fusion: remove dead code

---

airdata/WindEstimator.cpp
airdata/WindEstimator.hpp

The WindEstimator class uses an enum to index into its _state vector. However, in a few places (lines 166, 170, 171, 239 and 241), it mistakenly uses those enums as if they are variables representing the states, entirely corrupting the validity of the math.  
This change fixes that and also renames the enums using a style less likely to be mistaken for local variables in the future.

WindEstimator: Fix incorrect _state accessing, clarify enums

---

EKF/ekf.h

Even if the non_zeros() function is static constexpr, gcc (10.2) does not like it.
Using sizeof...(Idxs) fixes the error.
Thanks @jkflying for the help.

ekf: fix variable length array error

---

EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
EKF/optflow_fusion.cpp

This is something I always needed when working with optical flow sensors. It allows to easily fine tune the delay and scale factor of the optical flow measurements to get the best possible gyro compensation.
It's also extremely useful to see if the measurements make sense because looking at flow innovations isn't really intuitive.
Here's an example of what you can get in the log (I'll make the corresponding firmware PR to add the logging part):

Optical flow: compute velociy from corrected flow data for logging

---

EKF/common.h
EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.h
EKF/ekf_helper.cpp

Does this make sense as a fault status bit? We don't necessarily have all the input data logged at full rate so I wanted to capture this somewhere within ecl/EKF status.

EKF: add fault status bit for clipping

---

EKF/airspeed_fusion.cpp
EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
EKF/mag_control.cpp
EKF/terrain_estimator.cpp

This saves about 1.34 kB of flash largely by removing the virtual methods from `EstimatorInterface`. They aren't needed because users of ECL like PX4-Autopilot use `Ekf` (inherits EstimatorInterface) directly. It might be worth reviewing the high level design intent of the separation between `EstimatorInterface` and `Ekf`, but for now it's a decent flash savings for minimal effort. 
``` Console
VM SIZE    
-------------- 
[NEW]    +716    Ekf::compensateBaroForDynamicPressure(float) const
[NEW]    +454    Ekf::get_ekf_soln_status(unsigned short*) const
[NEW]    +336    Ekf::get_ekf_vel_accuracy(float*, float*) const
[NEW]    +284    Ekf::get_innovation_test_status(unsigned short&, float&, float&, float&, float&, float&, float&, float&) const
[NEW]    +212 …
```

EKF: remove virtual getters from estimator_interface

---

EKF/estimator_interface.h

This is for convenient usage outside of ECL.
``` C++
filter_control_status_u control_status;
_ekf.get_control_mode(&control_status.value);
_preflt_checker.setUsingGpsAiding(control_status.flags.gps);
```
``` C++
_preflt_checker.setUsingGpsAiding(_ekf.control_status_flags().gps);
```

EKF: add const reference getters for status flags

---

EKF/common.h
EKF/control.cpp
EKF/ekf.cpp
EKF/sensor_range_finder.hpp

This will allow to adjust the hysteresis time based on the distance sensor performances.
For distance sensors that can't read high distances (i.e. >10m) waiting 1s or more before fusing the data might lead to hard landings during auto descends.

range_finder: parametrize range sensor quality hysteresis time

---

EKF/gps_checks.cpp

Introduced in https://github.com/PX4/PX4-ECL/pull/851
TODO: add unit test

Use strength in Gauss

---

EKF/RingBuffer.h
EKF/common.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/estimator_interface.h
test/sensor_simulator/baro.cpp
test/sensor_simulator/ekf_wrapper.cpp
test/sensor_simulator/mag.cpp
test/sensor_simulator/vio.cpp
test/test_EKF_measurementSampling.cpp
test/test_EKF_ringbuffer.cpp
test/test_SensorRangeFinder.cpp

- allocate IMU and output buffers on construction according to defaults
- determine buffer max time delay based on configuration parameters
- reorder flowSample and extVisionSample to minimize padding
- adjust parameter defaults to match PX4-Autopilot
This was broken out of https://github.com/PX4/PX4-ECL/pull/935.
Saves a bit of memory (depending on configuration) and about 2 kB of flash (surprisingly).

EKF: RingBuffer minor improvements

---

EKF/airspeed_fusion.cpp
EKF/control.cpp
EKF/ekf.h
EKF/estimator_interface.cpp
EKF/estimator_interface.h

During SITL testing with gazebo_plane it was observed that if sideslip fusion was disabled by setting EKF2_FUSE_BETA=0 and the GPS stopped by first setting the parameter SYS_FAILURE_EN = 1 followed by pxh> failure gps off, then the following occurred:
The vehicle_local_position.valid_xy flag periodically goes true true and wind states experience large variations after the EKF had reverted back to a non-position estimation mode - see below.
These changes fix this by ensuring that a valid local position can never be reported true and the wind states and covariances are deactivated  if the EKF is in a non-position mode - see below
Note that setting EKF2_FUSE_BETA = 1 is recommended for fixed wing flight in the majority of applications due to the extended dead-reckoning in excess of 5 minutes …

Fix GPS loss dead reckoning behaviour

---

.github/workflows/functional_change_indicator.yml
.github/workflows/update_change_indicator.yml
test/change_indication/iris_gps.csv

The change indication is a nice tool to check if a proposed change does not introduce a functional change. It only covers limited scenarios, so it is by no means sufficient proof that there is no functional change introduced. The change indication requires to update certain csv files each time a functional change is made. This is a very delicate process, as the local build environment (compiler version, ...) has to match the CI build environment closely. Using docker containers is an alternative to produce correct change indication files. However, this involves many steps and is laborious. 
This PR adds another Github action, that updates the change indication on push, commits it, and pushes it to the remote branch.  The commit has the name `[AUTO COMMIT] update change indication`.  As it …

Auto update change indication

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.cpp
EKF/optflow_fusion.cpp
test/sensor_simulator/flow.cpp
test/sensor_simulator/sensor_simulator.cpp
test/test_EKF_flow.cpp
test/test_EKF_fusionLogic.cpp

I tried to untangle a bit the flow selection logic to make it more readable. At the same time the `resetToFlowVelocityInAir` unit test got fixed.
fixes https://github.com/PX4/PX4-ECL/issues/926
Currently no SITL/real tests

flow: restructure optical flow control logic

---

EKF/estimator_interface.h
test/sensor_simulator/ekf_wrapper.cpp
test/test_EKF_basics.cpp

- the fault status union exceeded 16 bits, but the getter was get_filter_fault_status(uint16_t *val)
PX4-Autopilot side the fault status was being clobbered.

EKF: update control status and fault status getters

---

EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.h
EKF/ekf_helper.cpp

Review commit-by-commit.
For some reason, the GPS position variance was fused with an accuracy of `1.5 x reported vertical position accuracy` (introduced here: https://github.com/PX4/PX4-ECL/commit/6b2e2dba909a44430dc3879e73e990231fcc2206#diff-4fbcbe3d9e3bd3fad671899aab33b57ee060d253a71a7c45e9acb78c2d297d22R125-R128).
To me, it seems to be from a copy-pasta of the GPS vertical speed fusion, where the vertical speed accuracy needs to be computed as `1.5 x reported horizontal speed accuracy`. (https://github.com/PX4/PX4-ECL/blob/fbf67bdef99f6033ce6c1fb6736cd7bf67020602/EKF/control.cpp#L698-L699).

Fix GPS altitude variance computation

---

EKF/control.cpp
EKF/estimator_interface.cpp

The combination of airspeed and sideslip fusion acts to constrain horizontal velocity drift with wind relative dead reckoning, however this was not being recognised in the code.  This change treats the combination of airspeed and sideslip fusion as an equivalent horizontal velocity aiding source and ensures the solution status velocity_horiz flag will remain true if a fixed wing aircraft with airspeed and sideslip fusion loses GPS.

EKF: Treat combined sideslip and airspeed as a horizontal aiding source

---

EKF/Sensor.hpp
EKF/control.cpp
EKF/sensor_range_finder.cpp
EKF/sensor_range_finder.hpp
test/test_EKF_fusionLogic.cpp

The failsafe from rng height to baro height should occur after a reset
to baro triggered by the controlHeightSensorTimeouts function and not in
the fusion selector.
Until now, the EKF was fusing baro measurements between rng updates if
the range finder ODR was slower than the EKF update rate. This is not
the case anymore as the height reset occurs after 5 seconds.
The unit test has been extended to show this behavior.
fixes https://github.com/PX4/PX4-ECL/issues/958

rng height: reset to baro using common logic

---

EKF/ekf.h
EKF/ekf_helper.cpp
EKF/gps_checks.cpp

Hi @dagar ,
This PR reverts the deletion of the `getEkfGlobalOrigin` method for the global origin and simplifies/aligns its' usage and naming convention with your added `setEkfGlobalOrigin` method.  I will continue iterating with you on the corresponding PX4-Autopilot PR [#16544](https://github.com/PX4/PX4-Autopilot/pull/16544)
Please let me know what questions/modifications you would like addressed with this PR.
Thanks!
-Mark

Retain getEkfGlobalOrigin() method and refactor for simplicity, standardize naming convention with setEkfGlobalOrigin().

---

EKF/control.cpp
EKF/ekf.h
EKF/vel_pos_fusion.cpp

This change fixes a bug that allowed IMU gyro errors large enough to cause large tilt errors prior to start of aiding, to not result in large innovation test ratios. When only 2 IMU's are being used in a multi EKF setup, this results in the EKF selector not switching as the test ratio due to the diverging position stays a small number due to the large gate, eg:
Replay currently does not work on logs with multiple EKF's so I have been unable to test on the log that shows the defect.
TODO - test on a multi EKF setup with EKF2_MULTI_IMU=2 and SENS_ IMU_MNODE = 0 and while on ground without GPS, set CAL_GYRO0_XOFF to 0.5

EKF: Fix reporting of non position mode innovation test levels

---

EKF/ekf.cpp
EKF/ekf.h
EKF/terrain_estimator.cpp

In many places, the main EKF assumes that a recent `_time_last_of_fuse` means that the horizontal velocity is constrained by flow fusion. This is not the case as this variable was also used in the terrain estimator.
Also, even if in most places the flow fusion flag is checked in addition to `_time_last_of_fuse`, there is a time window where this condition can be true since the flag can change instantaneously.
This PR adds a new `_time_last_flow_terrain_fuse` to avoid confusion and bugs related to this multiple use of the same variable.

flow terrain: use dedicated variable for last fusion time

---

EKF/common.h
EKF/control.cpp
EKF/covariance.cpp
EKF/ekf.h
EKF/vel_pos_fusion.cpp

Improvement in response to Issue #835 
Extends early reset to recover from bad vibration induced loss of height estimation to includes sensor combinations other than Baro for height and GPS for vertical velocity.
When height and vertical velocity sensing iis from the same sensor (GPS or EV), IMU clipping is used to adjudicate.

EKF: Use IMU clipping to adjudicate bad accel data check

---

EKF/gps_checks.cpp

We had cases at Wingtra when the GPS checks passed before the filter initialized
```
15.50 0:00:15 INFO: 2021_02_10_12_44_52: [ecl/EKF] EKF GPS checks passed (WGS-84 origin set)
...
33.50 0:00:33 INFO: 2021_02_10_12_45_10: [ecl/EKF] EKF aligned, (pressure height, IMU buf: 10, OBS buf: 6)
...
33.52 0:00:33 INFO: 2021_02_10_12_45_10: [ecl/EKF] EKF commencing GPS fusion
```
Resulting from that is that the global position altitude reference (_gps_alt_ref) is reset in EKF/ekf.cpp > initialiseFilter() after being initialized in EKF/gps_checks.cpp > collect_gps(). And then the global altitude is wrong.
The solution proposed would be to wait for the filter to be initialized before setting the global references. Another possibility would be to force the reset of all references …

Waiting for the filter to be initialized to set global origin

---

EKF/control.cpp
EKF/ekf.h
EKF/mag_control.cpp
test/test_EKF_fusionLogic.cpp
test/test_EKF_gps_yaw.cpp

**Issue found**
I have been flying an UAV with an intermittent external vision and I found that heading state did not reset to magnetometer when external vision failed. 
**Solution**
In _mag_control.cpp_ I added a logic which is aware of other sources of heading may stop contributing measures. Also, I extended the tests to catch that bug.

Heading reset to magnetometer from GPS or EV

---

EKF/ekf.h

From the discussion in https://github.com/PX4/PX4-ECL/pull/961#issuecomment-779259966.
This makes it convenient to access the reset counts directly (https://github.com/PX4/PX4-Autopilot/pull/16856) without having to copy the actual change.

EKF add const state reset status access

---

EKF/control.cpp
EKF/ekf.h
EKF/ekf_helper.cpp
EKF/estimator_interface.h
EKF/gps_checks.cpp
test/sensor_simulator/gps.cpp
test/sensor_simulator/gps.h
test/sensor_simulator/sensor_simulator.cpp
test/sensor_simulator/sensor_simulator.h
test/test_EKF_basics.cpp

- new `bool setGlobalOrigin(const double latitude, const double longitude, const float altitude);` intended to be used Firmware side with things like Mavlink SET_GPS_GLOBAL_ORIGIN
- replace `bool get_ekf_origin(uint64_t *origin_time, map_projection_reference_s *origin_pos, float *origin_alt) const;` with const reference inlined getters
- new vertical position reset helper `void resetVerticalPositionTo(const float &new_vert_pos);`
FYI @mcsauder

EKF set global origin

---

EKF/ekf_helper.cpp

Reported height test ratio was always equal to the position test ratio.
I fixed that using the correct index in _gps_pos_test_ratio vector.
I also add all height sources in this status.
Test: On the ground with baro as main height source, when I blow on my autopilot, the height test ratio increase.

Height test ratio status

---

EKF/control.cpp

- skip range aid velocity check when horizontal aiding isn't active
- added new tilt limit check when horizontal aiding isn't active (currently 15 degrees somewhat arbitrarily)

allow range aid without horizontal aiding

---

EKF/common.h
EKF/control.cpp
EKF/covariance.cpp
EKF/ekf_helper.cpp
EKF/estimator_interface.h
EKF/gps_checks.cpp
EKF/gps_yaw_fusion.cpp
EKF/mag_fusion.cpp
ecl.h

This is a first step in enabling the various printed event messages to be removed 
See https://github.com/PX4/PX4-Autopilot/pull/17012 for PX4-Autopilot changes required to utilise this.
See https://github.com/PX4/PX4-ECL/pull/961 for addtional context.

Enable access to EKF information and warning events

---

EKF/common.h
EKF/ekf.h
EKF/terrain_estimator.cpp

Hi all!
This doesn't change any behaviour, but it keeps track of and exposes a reset counter for the terrain estimator. 
The reset counter can be used on the autopilot side to reset the terrain height setpoints in sync, which in turn can make it possible to make the terrain following / holding altitude modes more robust over uneven terrain, especially manmade and indoor environments. I intend to open a follow-up pull request on the PX4-Autopilot repo for that.

Terrain estimator reset counter

---

EKF/EKFGSF_yaw.cpp
EKF/control.cpp

The yaw estimator should use the same maximum GNSS speed accuracy controlled by the user-defined parameter.

gps sacc: apply same minimum for EKF2 and yaw estimator

---

EKF/control.cpp
EKF/ekf_helper.cpp
EKF/vel_pos_fusion.cpp
test/test_EKF_fusionLogic.cpp

This implements a fallback mechanism to RangeFinder (if existing) and then to Baro, if vision is selected as primary EKF2 height source in case of vision timeouts.
fixes https://github.com/PX4/PX4-Autopilot/issues/16858

Height source vision: Fallback to rangefinder if available

---

EKF/common.h

There are currently 18 fault status bits and the value was only uint16_t.

EKF increase fault flags value size

---

EKF/control.cpp

Although `controlHeightSensorTimeouts()` switched to` rng_hgt` mode correctly as soon as an ev timeout happens, range finder height fusion is not performed as `rng_hgt` is not allowed if vision is the primary height source. This PR allows range finder height fusion even if vision is selected as primary height source.
Relates to https://github.com/PX4/PX4-ECL/pull/994

Allow RangeFinder fusion in vision height mode (Fix for #994)

---

EKF/control.cpp

In the normal and lowlight mode for the PAW3902/3 sensor, the ODR is 66Hz, while in super lowlight mode it is 50Hz. See plots for the switching in a typical flight.
The IMU ODR vs flow ODR mismatch threshold was too conservative for the 66Hz ODR, since https://github.com/PX4/PX4-ECL/pull/928. The EKF would keep waiting for the data to line up and never fuse measurements.

EKF: increase allowed difference between flow and gyro ODRs

---

EKF/control.cpp

A value of 1m/s was too conservative and the EKF takes too much time to trigger a yaw reset. The value can be safely reduced because the threshold is computed using the accuracy of the measurement and estimate before being limited by this value.
Tested in SITL, worked as expected.

yaw emmergency reset: reduce minimum vector length to compute yaw error

---

EKF/common.h

some parameters of the ECL can't be changed by PX4 parameter, and having them on the 'parameters' struct might confuse.
But at least having them with const attribute, make that a bit more clear.
If in later versions one become changeable by parameter, just need to remove the const.
There might be other consideration I might not aware of, so fell free to reject the PR.

const parameters to const attribute

---

EKF/airspeed_fusion.cpp

This caused bad initialization of the wind estimate on tailsitters just after the transition to fixedwing flight where the pitch is at -90 degrees.

Fix wind estimate initialization for tailsitters

---

test/test_EKF_withReplayData.cpp

fixes compilation failure introduced by https://github.com/PX4/PX4-ECL/pull/1010

test_replay: remove setting read-only parameter

---

EKF/covariance.cpp
EKF/ekf.h
EKF/mag_fusion.cpp

When the mag is pulled away before takeoff, the EKF can end up learning a bad yaw gyro bias. This bad gyro bias makes the estimated heading spin and even if the bias continues to be learned, it can end up being stuck in limit cycle due to the innovation changing its sign every time the heading estimate overshoots the measurement.
To prevent this, the Z gyro bias variance is reset when the mag heading fusion test ratio fails on ground.
Issue reproduced in SITL (the heading spins around and the Z gyro bias is stuck in a limit cycle):
With this PR (when reaching a test ratio of 1, the variance is reset, allowing the bias to re-converge quickly):

heading_fusion: fix yaw gyro bias oscillation on ground

---

EKF/ekf_helper.cpp
test/test_EKF_externalVision.cpp

Otherwise, the old rotation matrix is used and not updated anymore because the EKF is fusing EV yaw data.
Note that this issue only occurs when `MASK_ROTATE_EV` and `MASK_EV_YAW` are set at the same time (because otherwise, if `MASK_ROTATE_EV` isn't set, the wrong rotation matrix is never used).
Explanation of the race condition:
1. Initially, EV yaw fusion isn't active, the rotation matrix between the local frame (NED, initialized using mag) and EV frame is computed
2. EV yaw starts, the yaw estimate is reset to the EV yaw
3. During the fusion, if `MASK_ROTATE_EV` is set, the data is rotated using the rotation matrix computed in 1 (which is now wrong)
4. Because EV yaw fusion is now active, the rotation matrix isn't updated anymore
Added a unit test that triggers the race condition above …

EV_yaw: reset ev_to_ekf to identity when yaw is reset to EV

---

EKF/common.h
EKF/estimator_interface.cpp

it seems that if some observes are not used, still their delay time parameters are used and might increase the delay buffers.
this pr should check if observes are used and if not, ignore their delay parameters.
1. airspeed - seems that if param_ekf2_arsp_thr is >0 it can be used
2. baro - I couldn't find (if) there is parameter that can imply it used or not. so there is still `if(??)` on the code !
3. aux velocity -  I couldn't find (if) there is parameter that can imply it used or not. so there is still `if(??)` on the code !

delay time: potentially reduce delay time if airspeed is not used

---

EKF/common.h
EKF/drag_fusion.cpp
EKF/python/ekf_derivation/main.py

This adds an additional drag term to the aerodynamic drag observation model use for multi-copter wind estimation that captures the momentum drag from lift propellers that varies with speed not speed^2 and is the dominant drag term for most of the multi-rotor flight envelope.
TODO - tuning on an example airframe
See https://github.com/priseborough/PX4-Autopilot/tree/pr-ekf_momentum_drag for PX4-Autopilot changes that expose the tuning parameter to the user.
This was tested using SITL gazebo by adding a 5m/s wind which produced a 1.8 m/s/s lateral body specific force.
For the first test the momentum drag model was tested using the following parameters
EKF2_AID_MASK = 33
EKF2_MCOEF = 0.36
EKF2_BCOEF_X,Y = 0 (disabled)
which gave the expected result:
The ballistic coefficient drag model was …

EKF: Extend drag fusion to include propeller momentum drag

---

EKF/ekf.h

- otherwise checkVerticalAccelerationHealth() can fail if GPS or EV aren't available to correctly set vertical velocity fusion time and innovation ratio

EKF: initialize vertical position and velocity variables
